---
swagger: "2.0"
info:
  version: "1.0.0"
  title: "Beyond REST API"
host: "api-shop.beyondshop.cloud"
basePath: "/api"
schemes:
- "https"
paths:
  /:
    get:
      summary: "Index Unauthorized"
      description: ""
      operationId: "index-unauthorized"
  /add-ons/installed:
    get:
      tags:
      - "add-ons"
      summary: "List App Installations"
      description: ""
      operationId: "add-on-installations"
      security:
      - oauth2_accessCode:
        - "adon:r"
      - oauth2_application:
        - "adon:r"
  /add-ons/installed/{id}:
    delete:
      tags:
      - "add-ons"
      summary: "Uninstall Official App"
      description: ""
      operationId: "add-on-delete"
      security:
      - oauth2_accessCode:
        - "adon:m"
      - oauth2_application:
        - "adon:m"
  /carts:
    post:
      tags:
      - "carts"
      summary: "Create Cart"
      description: ""
      operationId: "cart-create"
  /carts/{cartId}:
    get:
      tags:
      - "carts"
      summary: "Get Cart"
      description: ""
      operationId: "cart-get"
    delete:
      tags:
      - "carts"
      summary: "Delete Cart"
      description: ""
      operationId: "cart-delete"
  /carts/{cartId}/billing-address:
    put:
      tags:
      - "carts"
      summary: "Set Billing Address"
      description: ""
      operationId: "cart-set-billing-address"
  /carts/{cartId}/create-payment:
    post:
      tags:
      - "carts"
      summary: "Create Payment"
      description: ""
      operationId: "cart-create-payment"
  /carts/{cartId}/create-payment-and-order:
    post:
      tags:
      - "carts"
      summary: "Create Payment and Order"
      description: ""
      operationId: "cart-create-payment-and-order"
  /carts/{cartId}/line-items:
    post:
      tags:
      - "carts"
      summary: "Add Line Item"
      description: ""
      operationId: "cart-add-line-item"
    put:
      tags:
      - "carts"
      summary: "Set Line Items"
      description: ""
      operationId: "cart-set-line-items"
  /carts/{cartId}/order:
    post:
      tags:
      - "carts"
      summary: "Order Cart"
      description: ""
      operationId: "cart-order"
  /carts/{cartId}/payment-methods:
    get:
      tags:
      - "carts"
      summary: "Get Payment Methods of Cart"
      description: ""
      operationId: "cart-get-payment-methods"
  /carts/{cartId}/shipping-address:
    put:
      tags:
      - "carts"
      summary: "Set Shipping Address"
      description: ""
      operationId: "cart-set-shipping-address"
  /carts/{cartId}/shipping-methods:
    get:
      tags:
      - "carts"
      summary: "Get Shipping Methods of Cart"
      description: ""
      operationId: "cart-get-shipping-methods"
  /carts/{cartId}/line-items/{lineItemId}:
    put:
      tags:
      - "carts"
      summary: "Replace Line Items"
      description: ""
      operationId: "cart-replace-line-item"
    delete:
      tags:
      - "carts"
      summary: "Delete Line Items"
      description: ""
      operationId: "cart-delete-line-item"
  /carts/{cartId}/payment-methods/current:
    get:
      tags:
      - "carts"
      summary: "Get Payment Method of Cart"
      description: ""
      operationId: "cart-get-payment-methods-current"
    put:
      tags:
      - "carts"
      summary: "Set Payment Method of Cart"
      description: ""
      operationId: "cart-set-payment-methods-current"
  /carts/{cartId}/payment-methods/default:
    put:
      tags:
      - "carts"
      summary: "Set Default Payment Method"
      description: ""
      operationId: "cart-set-payment-methods-default"
  /carts/{cartId}/shipping-methods/current:
    get:
      tags:
      - "carts"
      summary: "Get Shipping Method of Cart"
      description: ""
      operationId: "cart-get-shipping-methods-current"
    put:
      tags:
      - "carts"
      summary: "Set Shipping Method of Cart"
      description: ""
      operationId: "cart-set-shipping-methods-current"
  /carts/{cartId}/shipping-methods/default:
    put:
      tags:
      - "carts"
      summary: "Set Default Shipping Method"
      description: ""
      operationId: "cart-set-shipping-methods-default"
  /categories:
    get:
      tags:
      - "categories"
      summary: "List Categories"
      description: ""
      operationId: "categories-list"
      security:
      - oauth2_accessCode:
        - "catg:r"
      - oauth2_application:
        - "catg:r"
    post:
      tags:
      - "categories"
      summary: "Create Category"
      description: ""
      operationId: "category-create"
      security:
      - oauth2_accessCode:
        - "catg:c"
      - oauth2_application:
        - "catg:c"
  /categories/{id}:
    get:
      tags:
      - "categories"
      summary: "Get Category"
      description: ""
      operationId: "category-get"
      security:
      - oauth2_accessCode:
        - "catg:r"
      - oauth2_application:
        - "catg:r"
    put:
      tags:
      - "categories"
      summary: "Update Category"
      description: ""
      operationId: "category-put"
      security:
      - oauth2_accessCode:
        - "catg:u"
      - oauth2_application:
        - "catg:u"
    delete:
      tags:
      - "categories"
      summary: "Delete Category"
      description: ""
      operationId: "category-delete"
      security:
      - oauth2_accessCode:
        - "catg:d"
      - oauth2_application:
        - "catg:d"
    patch:
      tags:
      - "categories"
      summary: "Update Category"
      description: ""
      operationId: "category-patch-jsonpatch"
      security:
      - oauth2_accessCode:
        - "catg:u"
      - oauth2_application:
        - "catg:u"
  /checkout-settings:
    get:
      tags:
      - "checkout-settings"
      summary: "Get Checkout Settings"
      description: ""
      operationId: "checkout-settings-get"
      security:
      - oauth2_accessCode:
        - "cset:r"
      - oauth2_application:
        - "cset:r"
    put:
      tags:
      - "checkout-settings"
      summary: "Update Checkout Settings"
      description: ""
      operationId: "checkout-settings-update"
      security:
      - oauth2_accessCode:
        - "cset:u"
      - oauth2_application:
        - "cset:u"
  /configuration/invoice-number:
    get:
      tags:
      - "configuration"
      summary: "Get Invoice Number"
      description: ""
      operationId: "invoice-number-get"
      security:
      - oauth2_accessCode:
        - "invn:r"
      - oauth2_application:
        - "invn:r"
    put:
      tags:
      - "configuration"
      summary: "Update Invoice Number"
      description: ""
      operationId: "invoice-number-put"
      security:
      - oauth2_accessCode:
        - "invn:u"
      - oauth2_application:
        - "invn:u"
    patch:
      tags:
      - "configuration"
      summary: "Update Invoice Number"
      description: ""
      operationId: "invoice-number-patch"
      security:
      - oauth2_accessCode:
        - "invn:u"
      - oauth2_application:
        - "invn:u"
  /configuration/order-number:
    get:
      tags:
      - "configuration"
      summary: "Get Order Number"
      description: ""
      operationId: "order-number-get"
      security:
      - oauth2_accessCode:
        - "ordn:r"
      - oauth2_application:
        - "ordn:r"
    put:
      tags:
      - "configuration"
      summary: "Update Order Number"
      description: ""
      operationId: "order-number-put"
      security:
      - oauth2_accessCode:
        - "ordn:u"
      - oauth2_application:
        - "ordn:u"
    patch:
      tags:
      - "configuration"
      summary: "Update Order Number"
      description: ""
      operationId: "order-number-patch"
      security:
      - oauth2_accessCode:
        - "ordn:u"
      - oauth2_application:
        - "ordn:u"
  /google-shopping/access-data:
    get:
      tags:
      - "google-shopping"
      summary: "Get Access Data"
      description: ""
      operationId: "access-data-get"
      security:
      - oauth2_accessCode:
        - "gsad:r"
      - oauth2_application:
        - "gsad:r"
    post:
      tags:
      - "google-shopping"
      summary: "Create Access Data"
      description: ""
      operationId: "access-data-create-with-auth-url"
      security:
      - oauth2_accessCode:
        - "gsad:c"
      - oauth2_application:
        - "gsad:c"
    put:
      tags:
      - "google-shopping"
      summary: "Update Access Data"
      description: ""
      operationId: "access-data-put"
      security:
      - oauth2_accessCode:
        - "gsad:u"
      - oauth2_application:
        - "gsad:u"
    delete:
      tags:
      - "google-shopping"
      summary: "Delete Access Data"
      description: ""
      operationId: "access-data-delete"
      security:
      - oauth2_accessCode:
        - "gsad:d"
      - oauth2_application:
        - "gsad:d"
  /google-shopping/products:
    get:
      tags:
      - "google-shopping"
      summary: "List Google Shopping Products"
      description: ""
      operationId: "google-shopping-products-list"
      security:
      - oauth2_accessCode:
        - "gspr:r"
      - oauth2_application:
        - "gspr:r"
    post:
      tags:
      - "google-shopping"
      summary: "Create Google Shopping Product"
      description: ""
      operationId: "google-shopping-product-post"
      security:
      - oauth2_accessCode:
        - "gspr:c"
      - oauth2_application:
        - "gspr:c"
  /google-shopping/site-verification:
    get:
      tags:
      - "google-shopping"
      summary: "Retrieve Site Verification Token"
      description: ""
      operationId: "site-verification-token-get"
  /google-shopping/taxonomy:
    get:
      tags:
      - "google-shopping"
      summary: "List Taxonomy"
      description: ""
      operationId: "taxonomy-get"
  /google-shopping/products/publish:
    post:
      tags:
      - "google-shopping"
      summary: "Publish List of Google Shopping Products"
      description: ""
      operationId: "google-shopping-products-publish-list"
      security:
      - oauth2_accessCode:
        - "gspr:u"
      - oauth2_application:
        - "gspr:u"
  /google-shopping/products/{id}:
    get:
      tags:
      - "google-shopping"
      summary: "Get Google Shopping Product"
      description: ""
      operationId: "google-shopping-product-get"
      security:
      - oauth2_accessCode:
        - "gspr:r"
      - oauth2_application:
        - "gspr:r"
    put:
      tags:
      - "google-shopping"
      summary: "Update Google Shopping Product"
      description: ""
      operationId: "google-shopping-product-put"
      security:
      - oauth2_accessCode:
        - "gspr:u"
      - oauth2_application:
        - "gspr:u"
    delete:
      tags:
      - "google-shopping"
      summary: "Delete Google Shopping Product"
      description: ""
      operationId: "google-shopping-product-delete"
      security:
      - oauth2_accessCode:
        - "gspr:d"
      - oauth2_application:
        - "gspr:d"
  /google-shopping/products/{id}/publish:
    post:
      tags:
      - "google-shopping"
      summary: "Publish Google Shopping Product"
      description: ""
      operationId: "google-shopping-product-publish"
      security:
      - oauth2_accessCode:
        - "gspr:u"
      - oauth2_application:
        - "gspr:u"
  /google-shopping/products/{id}/unpublish:
    post:
      tags:
      - "google-shopping"
      summary: "Unpublish Google Shopping Product"
      description: ""
      operationId: "google-shopping-product-unpublish"
      security:
      - oauth2_accessCode:
        - "gspr:u"
      - oauth2_application:
        - "gspr:u"
  /legal-content:
    get:
      tags:
      - "legal-content"
      summary: "List Legal Content"
      description: ""
      operationId: "merchant-legal-content-list"
  /legal-content/{name}:
    get:
      tags:
      - "legal-content"
      summary: "Get Legal Content"
      description: ""
      operationId: "merchant-legal-content-get"
    put:
      tags:
      - "legal-content"
      summary: "Update Legal Content"
      description: ""
      operationId: "merchant-legal-content-edit"
      security:
      - oauth2_accessCode:
        - "lcnt:u"
      - oauth2_application:
        - "lcnt:u"
  /oauth/token:
    post:
      tags:
      - "oauth"
      summary: "Create a JsonWebToken"
      description: ""
      operationId: "oauth2-token-refresh"
      security:
      - basic: []
  /orders:
    get:
      tags:
      - "orders"
      summary: "List Orders"
      description: ""
      operationId: "orders-list"
      security:
      - oauth2_accessCode:
        - "ordr:r"
      - oauth2_application:
        - "ordr:r"
  /orders/{order-id}:
    get:
      tags:
      - "orders"
      summary: "Get Order"
      description: ""
      operationId: "order-get"
      security:
      - oauth2_accessCode:
        - "ordr:r"
      - oauth2_application:
        - "ordr:r"
  /orders/search/find-by-cart-id:
    get:
      tags:
      - "orders"
      summary: "Get Order By Cart Id"
      description: ""
      operationId: "order-get-by-cartid"
      security:
      - oauth2_accessCode:
        - "ordr:r"
      - oauth2_application:
        - "ordr:r"
  /orders/{id}/send-invoice:
    post:
      tags:
      - "orders"
      summary: "Send Invoice"
      description: ""
      operationId: "order-send-invoice"
      security:
      - oauth2_accessCode:
        - "ordr:u"
      - oauth2_application:
        - "ordr:u"
  /orders/{order-id}/billing-address:
    put:
      tags:
      - "orders"
      summary: "Update Billing Address"
      description: ""
      operationId: "order-update-billing-address"
      security:
      - oauth2_accessCode:
        - "ordr:u"
      - oauth2_application:
        - "ordr:u"
  /orders/{order-id}/create-invoice:
    post:
      tags:
      - "orders"
      summary: "Create Invoice"
      description: ""
      operationId: "order-create-invoice"
      security:
      - oauth2_accessCode:
        - "ordr:u"
      - oauth2_application:
        - "ordr:u"
  /orders/{order-id}/events:
    get:
      tags:
      - "orders"
      summary: "List Order Events"
      description: ""
      operationId: "order-events-list"
      security:
      - oauth2_accessCode:
        - "orde:r"
      - oauth2_application:
        - "orde:r"
  /orders/{order-id}/order-note:
    put:
      tags:
      - "orders"
      summary: "Update Order Note"
      description: ""
      operationId: "order-note-update"
      security:
      - oauth2_accessCode:
        - "ordr:u"
      - oauth2_application:
        - "ordr:u"
  /orders/{order-id}/processes:
    get:
      tags:
      - "orders"
      summary: "Get Order Processes"
      description: ""
      operationId: "get-order-processes"
      security:
      - oauth2_accessCode:
        - "ordp:r"
      - oauth2_application:
        - "ordp:r"
  /orders/{order-id}/shipping-address:
    put:
      tags:
      - "orders"
      summary: "Update Shipping Address"
      description: ""
      operationId: "order-update-shipping-address"
      security:
      - oauth2_accessCode:
        - "ordr:u"
      - oauth2_application:
        - "ordr:u"
  /orders/{order-id}/processes/refunds:
    get:
      tags:
      - "orders"
      summary: "List Refund Processes"
      description: ""
      operationId: "get-refund-processes"
      security:
      - oauth2_accessCode:
        - "rfpr:r"
      - oauth2_application:
        - "rfpr:r"
  /orders/{order-id}/processes/returns:
    get:
      tags:
      - "orders"
      summary: "List Return Processes"
      description: ""
      operationId: "get-return-processes"
      security:
      - oauth2_accessCode:
        - "rtpr:r"
      - oauth2_application:
        - "rtpr:r"
    post:
      tags:
      - "orders"
      summary: "Create Return Processes"
      description: ""
      operationId: "create-return-process"
      security:
      - oauth2_accessCode:
        - "rtpr:c"
      - oauth2_application:
        - "rtpr:c"
  /orders/{order-id}/processes/shippings:
    get:
      tags:
      - "orders"
      summary: "List Shipping Processes"
      description: ""
      operationId: "get-shipping-processes"
      security:
      - oauth2_accessCode:
        - "shpr:r"
      - oauth2_application:
        - "shpr:r"
    post:
      tags:
      - "orders"
      summary: "Create Shipping Process"
      description: ""
      operationId: "create-shipping-process"
      security:
      - oauth2_accessCode:
        - "shpr:c"
      - oauth2_application:
        - "shpr:c"
  /orders/{order-id}/processes/refunds/active:
    get:
      tags:
      - "orders"
      summary: "Get Active Refund Process"
      description: ""
      operationId: "get-active-refund-process"
      security:
      - oauth2_accessCode:
        - "rfpr:r"
      - oauth2_application:
        - "rfpr:r"
  /orders/{order-id}/processes/refunds/{id}:
    get:
      tags:
      - "orders"
      summary: "Get Refund Process"
      description: ""
      operationId: "get-refund-process"
      security:
      - oauth2_accessCode:
        - "rfpr:r"
      - oauth2_application:
        - "rfpr:r"
  /orders/{order-id}/processes/returns/{return-process-id}:
    get:
      tags:
      - "orders"
      summary: "Get Return Process"
      description: ""
      operationId: "get-return-process"
      security:
      - oauth2_accessCode:
        - "rtpr:r"
      - oauth2_application:
        - "rtpr:r"
  /orders/{order-id}/processes/shippings/{shipping-process-id}:
    get:
      tags:
      - "orders"
      summary: "Get Shipping Process"
      description: ""
      operationId: "get-shipping-process"
      security:
      - oauth2_accessCode:
        - "shpr:r"
      - oauth2_application:
        - "shpr:r"
  /orders/{order-id}/processes/refunds/active/mark-paid:
    post:
      tags:
      - "orders"
      summary: "Mark Refund Process Paid"
      description: ""
      operationId: "mark-refund-process-paid"
      security:
      - oauth2_accessCode:
        - "rfpr:u"
      - oauth2_application:
        - "rfpr:u"
  /orders/{order-id}/processes/shippings/{shipping-process-id}/mark-delivered:
    post:
      tags:
      - "orders"
      summary: "Mark Shipping Process Delivered"
      description: ""
      operationId: "mark-shipping-process-delivered"
      security:
      - oauth2_accessCode:
        - "shpr:u"
      - oauth2_application:
        - "shpr:u"
  /orders/{order-id}/processes/shippings/{shipping-process-id}/mark-shipped:
    post:
      tags:
      - "orders"
      summary: "Mark Shipping Process Shipped"
      description: ""
      operationId: "mark-shipping-process-shipped"
      security:
      - oauth2_accessCode:
        - "shpr:u"
      - oauth2_application:
        - "shpr:u"
  /payment-methods:
    get:
      tags:
      - "payment-methods"
      summary: "Get Payment Method"
      description: ""
      operationId: "payment-method-percentage-get"
      security:
      - oauth2_accessCode:
        - "pymt:r"
      - oauth2_application:
        - "pymt:r"
    post:
      tags:
      - "payment-methods"
      summary: "Create Payment Method"
      description: ""
      operationId: "payment-method-percentage-create"
      security:
      - oauth2_accessCode:
        - "pymt:c"
      - oauth2_application:
        - "pymt:c"
    put:
      tags:
      - "payment-methods"
      summary: "Sort Payment Methods"
      description: ""
      operationId: "payment-method-sort"
      security:
      - oauth2_accessCode:
        - "pymt:u"
      - oauth2_application:
        - "pymt:u"
  /payment-methods/{paymentMethodId}:
    get:
      tags:
      - "payment-methods"
      summary: "Get Payment Method"
      description: ""
      operationId: "payment-method-get"
      security:
      - oauth2_accessCode:
        - "pymt:r"
      - oauth2_application:
        - "pymt:r"
    put:
      tags:
      - "payment-methods"
      summary: "Update Payment Method"
      description: ""
      operationId: "payment-method-update"
      security:
      - oauth2_accessCode:
        - "pymt:u"
      - oauth2_application:
        - "pymt:u"
    delete:
      tags:
      - "payment-methods"
      summary: "Delete Payment Method"
      description: ""
      operationId: "payment-method-delete"
      security:
      - oauth2_accessCode:
        - "pymt:d"
      - oauth2_application:
        - "pymt:d"
  /payment-methods/{paymentMethodId}/activate:
    post:
      tags:
      - "payment-methods"
      summary: "Activate Payment Method"
      description: ""
      operationId: "activate-payment-method"
      security:
      - oauth2_accessCode:
        - "pymt:u"
      - oauth2_application:
        - "pymt:u"
  /payment-methods/{paymentMethodId}/deactivate:
    post:
      tags:
      - "payment-methods"
      summary: "Deactivate Payment Method"
      description: ""
      operationId: "deactivate-payment-method"
      security:
      - oauth2_accessCode:
        - "pymt:u"
      - oauth2_application:
        - "pymt:u"
  /payment-methods/{paymentMethodId}/payment-integration:
    put:
      tags:
      - "payment-methods"
      summary: "Set Payment Integration on Payment Method"
      description: ""
      operationId: "payment-method-set-payment-integration-ref"
      security:
      - oauth2_accessCode:
        - "pymi:m"
      - oauth2_application:
        - "pymi:m"
  /payment-signup/merchant-accounts/{paymentIntegration}:
    get:
      tags:
      - "payment-signup"
      summary: "Get Merchant Account"
      description: ""
      operationId: "merchant-account"
      security:
      - oauth2_accessCode:
        - "pymt:r"
      - oauth2_application:
        - "pymt:r"
    delete:
      tags:
      - "payment-signup"
      summary: "Disconnect Merchant Account"
      description: ""
      operationId: "disconnect"
      security:
      - oauth2_accessCode:
        - "pymt:r"
      - oauth2_application:
        - "pymt:r"
  /payment-signup/referrals/{paymentIntegration}:
    post:
      tags:
      - "payment-signup"
      summary: "Initiate Referral"
      description: ""
      operationId: "referrals"
      security:
      - oauth2_accessCode:
        - "pymt:r"
      - oauth2_application:
        - "pymt:r"
  /payments/{paymentId}/approve:
    post:
      tags:
      - "payments"
      summary: "Approve Payment"
      description: ""
      operationId: "payment-approve"
      security:
      - oauth2_accessCode:
        - "paym:m"
      - oauth2_application:
        - "paym:m"
  /payments/{paymentId}/cancel:
    post:
      tags:
      - "payments"
      summary: "Cancel Payment"
      description: ""
      operationId: "payment-cancel"
      security:
      - oauth2_accessCode:
        - "paym:m"
      - oauth2_application:
        - "paym:m"
  /payments/{paymentId}/fail:
    post:
      tags:
      - "payments"
      summary: "/payments/{paymentId}/fail"
      description: ""
      operationId: "payment-fail"
      security:
      - oauth2_accessCode:
        - "paym:m"
      - oauth2_application:
        - "paym:m"
  /payments/{paymentId}/status:
    post:
      tags:
      - "payments"
      summary: "Set Payment Status"
      description: ""
      operationId: "set-payment-status"
      security:
      - oauth2_accessCode:
        - "paym:m"
      - oauth2_application:
        - "paym:m"
  /private-apps:
    get:
      tags:
      - "private-apps"
      summary: "List Private Apps"
      description: ""
      operationId: "private-apps-list"
      security:
      - oauth2_accessCode:
        - "papp:m"
      - oauth2_application:
        - "papp:m"
    post:
      tags:
      - "private-apps"
      summary: "Create Private App"
      description: ""
      operationId: "private-apps-create"
      security:
      - oauth2_accessCode:
        - "papp:m"
      - oauth2_application:
        - "papp:m"
  /private-apps/{id}:
    get:
      tags:
      - "private-apps"
      summary: "Get Private App"
      description: ""
      operationId: "private-app-get"
      security:
      - oauth2_accessCode:
        - "papp:m"
      - oauth2_application:
        - "papp:m"
    put:
      tags:
      - "private-apps"
      summary: "Update Private App"
      description: ""
      operationId: "private-app-update"
      security:
      - oauth2_accessCode:
        - "papp:m"
      - oauth2_application:
        - "papp:m"
    delete:
      tags:
      - "private-apps"
      summary: "Delete Private App"
      description: ""
      operationId: "private-app-delete"
      security:
      - oauth2_accessCode:
        - "papp:m"
      - oauth2_application:
        - "papp:m"
  /private-apps/{id}/regenerate-client-secret:
    post:
      tags:
      - "private-apps"
      summary: "Regenerate Private App Client Secret"
      description: ""
      operationId: "private-app-regenerate-client-secret"
      security:
      - oauth2_accessCode:
        - "papp:m"
      - oauth2_application:
        - "papp:m"
  /private-apps/{id}/scopes:
    get:
      tags:
      - "private-apps"
      summary: "Get Private App Scopes"
      description: ""
      operationId: "private-app-scopes-get"
      security:
      - oauth2_accessCode:
        - "papp:m"
      - oauth2_application:
        - "papp:m"
    put:
      tags:
      - "private-apps"
      summary: "Update Private App Scopes"
      description: ""
      operationId: "private-app-scopes-update"
      security:
      - oauth2_accessCode:
        - "papp:m"
        - "ordr:r"
      - oauth2_application:
        - "papp:m"
        - "ordr:r"
  /product-attribute-definitions:
    get:
      tags:
      - "product-attribute-definitions"
      summary: "List Product Attribute Definitions"
      description: ""
      operationId: "product-attribute-definitions-list"
      security:
      - oauth2_accessCode:
        - "prad:r"
      - oauth2_application:
        - "prad:r"
    post:
      tags:
      - "product-attribute-definitions"
      summary: "Create Product Attribute Definition"
      description: ""
      operationId: "product-attribute-definitions-create"
      security:
      - oauth2_accessCode:
        - "prad:c"
      - oauth2_application:
        - "prad:c"
  /product-attribute-definitions/search:
    get:
      tags:
      - "product-attribute-definitions"
      summary: "Find Product Attribute Definitions"
      description: ""
      operationId: "product-attribute-definitions-search"
      security:
      - oauth2_accessCode:
        - "prad:r"
      - oauth2_application:
        - "prad:r"
  /product-attribute-definitions/{id}:
    get:
      tags:
      - "product-attribute-definitions"
      summary: "Get Product Attribute Definition"
      description: ""
      operationId: "product-attribute-definition-get"
      security:
      - oauth2_accessCode:
        - "prad:r"
      - oauth2_application:
        - "prad:r"
    delete:
      tags:
      - "product-attribute-definitions"
      summary: "Delete Product Attribute Definition"
      description: ""
      operationId: "product-attribute-definition-delete"
      security:
      - oauth2_accessCode:
        - "prad:d"
      - oauth2_application:
        - "prad:d"
    patch:
      tags:
      - "product-attribute-definitions"
      summary: "Update Product Attribute Definition"
      description: ""
      operationId: "product-attribute-definition-patch"
      security:
      - oauth2_accessCode:
        - "prad:u"
      - oauth2_application:
        - "prad:u"
  /product-attribute-definitions/search/find-by-namespace-and-name:
    get:
      tags:
      - "product-attribute-definitions"
      summary: "Find Product Attribute Definitions by Namespace and Name"
      description: ""
      operationId: "product-attribute-definitions-search-find-by-namespace-and-name"
      security:
      - oauth2_accessCode:
        - "prad:r"
      - oauth2_application:
        - "prad:r"
  /product-attribute-definitions/search/find-by-namespace-and-query:
    get:
      tags:
      - "product-attribute-definitions"
      summary: "Find Product Attribute Definitions by Namespace"
      description: ""
      operationId: "product-attribute-definitions-search-find-by-namespace-and-query"
      security:
      - oauth2_accessCode:
        - "prad:r"
      - oauth2_application:
        - "prad:r"
  /product-settings:
    get:
      tags:
      - "product-settings"
      summary: "Get Product Settings"
      description: ""
      operationId: "product-settings-get"
      security:
      - oauth2_accessCode:
        - "prst:r"
      - oauth2_application:
        - "prst:r"
    patch:
      tags:
      - "product-settings"
      summary: "Update Product Settings"
      description: ""
      operationId: "product-settings-patch"
      security:
      - oauth2_accessCode:
        - "prst:u"
      - oauth2_application:
        - "prst:u"
  /product-view/products:
    get:
      tags:
      - "product-view"
      summary: "List Product"
      description: ""
      operationId: "product-view-list"
  /product-view/categories/{categoryId}:
    get:
      tags:
      - "product-view"
      summary: "Get Enchanced View of Category"
      description: ""
      operationId: "category-get-enhanced"
  /product-view/products/{productId}:
    get:
      tags:
      - "product-view"
      summary: "Get Enchanced View of Product"
      description: ""
      operationId: "product-view-find-by-id-enhanced"
  /product-view/categories/search/find-by-label:
    get:
      tags:
      - "product-view"
      summary: "Find Category by Label"
      description: ""
      operationId: "category-get-by-label"
  /product-view/categories/search/find-by-product:
    get:
      tags:
      - "product-view"
      summary: "List Categories Assigned to Product"
      description: ""
      operationId: "product-view-find-categories-by-product"
  /product-view/categories/{categoryId}/products:
    get:
      tags:
      - "product-view"
      summary: "List Products of Category"
      description: ""
      operationId: "category-products"
  /product-view/products/search/find-available-tags:
    get:
      tags:
      - "product-view"
      summary: "List Available Tags "
      description: ""
      operationId: "product-view-find-available-tags"
  /product-view/products/search/find-by-category:
    get:
      tags:
      - "product-view"
      summary: "List Product by Category"
      description: ""
      operationId: "product-view-find-by-category"
  /product-view/products/search/find-by-query:
    post:
      tags:
      - "product-view"
      summary: "List Product by Query"
      description: ""
      operationId: "product-view-find-by-query"
  /product-view/products/search/find-by-search-term:
    get:
      tags:
      - "product-view"
      summary: "List Product by Term"
      description: ""
      operationId: "product-view-find-by-search-term"
  /product-view/products/search/find-by-tags:
    get:
      tags:
      - "product-view"
      summary: "List Product by Tags"
      description: ""
      operationId: "product-view-find-by-tags"
  /products:
    get:
      tags:
      - "products"
      summary: "List Products"
      description: ""
      operationId: "products-list"
      security:
      - oauth2_accessCode:
        - "prod:r"
      - oauth2_application:
        - "prod:r"
    post:
      tags:
      - "products"
      summary: "Create Product"
      description: ""
      operationId: "products-create"
      security:
      - oauth2_accessCode:
        - "prod:c"
      - oauth2_application:
        - "prod:c"
  /products/{productId}:
    get:
      tags:
      - "products"
      summary: "Get Product"
      description: ""
      operationId: "product-get"
      security:
      - oauth2_accessCode:
        - "prod:r"
      - oauth2_application:
        - "prod:r"
    delete:
      tags:
      - "products"
      summary: "Delete Product"
      description: ""
      operationId: "product-delete"
      security:
      - oauth2_accessCode:
        - "prod:d"
      - oauth2_application:
        - "prod:d"
    patch:
      tags:
      - "products"
      summary: "Update Product"
      description: ""
      operationId: "product-patch-json"
      security:
      - oauth2_accessCode:
        - "prod:u"
      - oauth2_application:
        - "prod:u"
  /products/search/find-attribute-string-values:
    get:
      tags:
      - "products"
      summary: "Find existing attribute values"
      description: ""
      operationId: "products-search-findAttributeStringValues"
      security:
      - oauth2_accessCode:
        - "prod:r"
      - oauth2_application:
        - "prod:r"
  /products/search/find-by-sku:
    get:
      tags:
      - "products"
      summary: "https://yourshop.api.urn/products/search/find-by-sku?sku=vino020"
      description: ""
      operationId: "products-search-findBySku"
      security:
      - oauth2_accessCode:
        - "prod:r"
      - oauth2_application:
        - "prod:r"
  /products/search/tags:
    get:
      tags:
      - "products"
      summary: "Find used tags"
      description: ""
      operationId: "find-tags-starts-with"
      security:
      - oauth2_accessCode:
        - "prod:r"
      - oauth2_application:
        - "prod:r"
  /products/{productId}/attachments:
    get:
      tags:
      - "products"
      summary: "List Product Attachments"
      description: ""
      operationId: "product-attachments-list"
      security:
      - oauth2_accessCode:
        - "prod:r"
      - oauth2_application:
        - "prod:r"
    post:
      tags:
      - "products"
      summary: "Create Product Attachment"
      description: ""
      operationId: "product-attachments-create"
      security:
      - oauth2_accessCode:
        - "prod:u"
      - oauth2_application:
        - "prod:u"
  /products/{productId}/attributes:
    get:
      tags:
      - "products"
      summary: "List Custom Product Attributes"
      description: ""
      operationId: "product-attributes-get-for-shop-locale"
      security:
      - oauth2_accessCode:
        - "prod:r"
      - oauth2_application:
        - "prod:r"
    post:
      tags:
      - "products"
      summary: "Create Custom Product Attribute"
      description: ""
      operationId: "product-custom-attribute-create"
      security:
      - oauth2_accessCode:
        - "prod:u"
      - oauth2_application:
        - "prod:u"
  /products/{productId}/availability:
    get:
      tags:
      - "products"
      summary: "Get Product Availability"
      description: ""
      operationId: "product-availability-get"
      security:
      - oauth2_accessCode:
        - "prda:r"
      - oauth2_application:
        - "prda:r"
  /products/{productId}/default-image:
    put:
      tags:
      - "products"
      summary: "Set Default Product Image"
      description: ""
      operationId: "product-images-set-default"
      security:
      - oauth2_accessCode:
        - "prod:u"
      - oauth2_application:
        - "prod:u"
  /products/{productId}/images:
    get:
      tags:
      - "products"
      summary: "List Product Images"
      description: ""
      operationId: "product-images-list"
      security:
      - oauth2_accessCode:
        - "prod:r"
      - oauth2_application:
        - "prod:r"
    post:
      tags:
      - "products"
      summary: "Create Product Image"
      description: ""
      operationId: "product-images-create"
      security:
      - oauth2_accessCode:
        - "prod:u"
      - oauth2_application:
        - "prod:u"
  /products/{productId}/attachments/{attachmentId}:
    get:
      tags:
      - "products"
      summary: "Get Product Attachment"
      description: ""
      operationId: "product-attachment-get"
      security:
      - oauth2_accessCode:
        - "prod:r"
      - oauth2_application:
        - "prod:r"
    delete:
      tags:
      - "products"
      summary: "Delete Product Attachment"
      description: ""
      operationId: "product-attachment-delete"
      security:
      - oauth2_accessCode:
        - "prod:u"
      - oauth2_application:
        - "prod:u"
  /products/{productId}/attributes/{namespace}:
    get:
      tags:
      - "products"
      summary: "List Custom Product Attributes by Namespace"
      description: ""
      operationId: "product-attributes-get-by-namespace-different-locale"
      security:
      - oauth2_accessCode:
        - "prod:r"
      - oauth2_application:
        - "prod:r"
  /products/{productId}/availability/adjust-available-stock:
    post:
      tags:
      - "products"
      summary: "Adjust Stock Level"
      description: ""
      operationId: "product-availability-adjust-available-stock"
      security:
      - oauth2_accessCode:
        - "prda:u"
      - oauth2_application:
        - "prda:u"
  /products/{productId}/availability/disable-purchasability:
    post:
      tags:
      - "products"
      summary: "Disable Purchasability"
      description: ""
      operationId: "product-availability-disable-purchasability"
      security:
      - oauth2_accessCode:
        - "prda:u"
      - oauth2_application:
        - "prda:u"
  /products/{productId}/availability/disable-stock-management:
    post:
      tags:
      - "products"
      summary: "Disable Stock Management"
      description: ""
      operationId: "product-availability-disable-stock-management"
      security:
      - oauth2_accessCode:
        - "prda:u"
      - oauth2_application:
        - "prda:u"
  /products/{productId}/availability/enable-purchasability:
    post:
      tags:
      - "products"
      summary: "Enable Purchasability"
      description: ""
      operationId: "product-availability-enable-purchasability"
      security:
      - oauth2_accessCode:
        - "prda:u"
      - oauth2_application:
        - "prda:u"
  /products/{productId}/availability/enable-stock-management:
    post:
      tags:
      - "products"
      summary: "Enable Stock Management"
      description: ""
      operationId: "product-availability-enable-stock-management"
      security:
      - oauth2_accessCode:
        - "prda:u"
      - oauth2_application:
        - "prda:u"
  /products/{productId}/availability/update-stock-threshold:
    post:
      tags:
      - "products"
      summary: "Update Reserve Stock"
      description: ""
      operationId: "product-availability-update-stock-threshold"
      security:
      - oauth2_accessCode:
        - "prda:u"
      - oauth2_application:
        - "prda:u"
  /products/{productId}/images/{imageId}:
    get:
      tags:
      - "products"
      summary: "Get Product Image"
      description: ""
      operationId: "product-image-get"
      security:
      - oauth2_accessCode:
        - "prod:r"
      - oauth2_application:
        - "prod:r"
    delete:
      tags:
      - "products"
      summary: "Delete Product Image"
      description: ""
      operationId: "product-image-delete"
      security:
      - oauth2_accessCode:
        - "prod:u"
      - oauth2_application:
        - "prod:u"
  /products/{productId}/attributes/{namespace}/{attributeName}:
    get:
      tags:
      - "products"
      summary: "List Custom Product Attributes by Namespace and Attribute Name"
      description: ""
      operationId: "product-attributes-get-by-namespace-name-different-locale"
      security:
      - oauth2_accessCode:
        - "prod:r"
      - oauth2_application:
        - "prod:r"
    delete:
      tags:
      - "products"
      summary: "Delete Custom Product Attribute"
      description: ""
      operationId: "product-attributes-delete"
      security:
      - oauth2_accessCode:
        - "prod:u"
      - oauth2_application:
        - "prod:u"
  /scopes:
    get:
      tags:
      - "scopes"
      summary: "List Scopes"
      description: ""
      operationId: "scopes-list"
      security:
      - oauth2_accessCode:
        - "scop:r"
      - oauth2_application:
        - "scop:r"
  /shipping-zones:
    get:
      tags:
      - "shipping-zones"
      summary: "List Shipping Zones"
      description: ""
      operationId: "shipping-zones-list"
      security:
      - oauth2_accessCode:
        - "shpz:r"
      - oauth2_application:
        - "shpz:r"
    post:
      tags:
      - "shipping-zones"
      summary: "Create Shipping Zone"
      description: ""
      operationId: "shipping-zones-create"
      security:
      - oauth2_accessCode:
        - "shpz:c"
      - oauth2_application:
        - "shpz:c"
    put:
      tags:
      - "shipping-zones"
      summary: "Sort Shipping Zones"
      description: ""
      operationId: "shipping-zones-sort"
      security:
      - oauth2_accessCode:
        - "shpz:u"
      - oauth2_application:
        - "shpz:u"
  /shipping-zones/{shippingZoneId}:
    get:
      tags:
      - "shipping-zones"
      summary: "Get Shipping Zone"
      description: ""
      operationId: "shipping-zone-get"
      security:
      - oauth2_accessCode:
        - "shpz:r"
      - oauth2_application:
        - "shpz:r"
    put:
      tags:
      - "shipping-zones"
      summary: "Update Shipping Zone"
      description: ""
      operationId: "shipping-zone-update"
      security:
      - oauth2_accessCode:
        - "shpz:u"
      - oauth2_application:
        - "shpz:u"
    delete:
      tags:
      - "shipping-zones"
      summary: "Delete Shipping Zone"
      description: ""
      operationId: "shipping-zone-delete"
      security:
      - oauth2_accessCode:
        - "shpz:d"
      - oauth2_application:
        - "shpz:d"
  /shipping-zones/search/find-all-serviceable-countries:
    get:
      tags:
      - "shipping-zones"
      summary: "Find Shipping Zone by Serviceable Countries"
      description: ""
      operationId: "shipping-zones-search-find-serviceable-countries"
  /shipping-zones/{shippingZoneId}/shipping-methods:
    get:
      tags:
      - "shipping-zones"
      summary: "Sort Shipping Method"
      description: ""
      operationId: "shipping-zones-shipping-methods-sort"
      security:
      - oauth2_accessCode:
        - "shpz:r"
      - oauth2_application:
        - "shpz:r"
    post:
      tags:
      - "shipping-zones"
      summary: "Create Shipping Method"
      description: ""
      operationId: "shipping-zones-shipping-methods-create-with-weight-based-price"
  /shipping-zones/{shippingZoneId}/shipping-methods/{shippingMethodId}:
    get:
      tags:
      - "shipping-zones"
      summary: "Get Shipping Method"
      description: ""
      operationId: "shipping-zones-shipping-method-get-with-weight-based-price"
      security:
      - oauth2_accessCode:
        - "shpz:r"
      - oauth2_application:
        - "shpz:r"
    put:
      tags:
      - "shipping-zones"
      summary: "Update Shipping Method"
      description: ""
      operationId: "shipping-zones-shipping-method-update"
      security:
      - oauth2_accessCode:
        - "shpz:u"
      - oauth2_application:
        - "shpz:u"
    delete:
      tags:
      - "shipping-zones"
      summary: "Delete Shipping Method"
      description: ""
      operationId: "shipping-zones-shipping-method-delete"
      security:
      - oauth2_accessCode:
        - "shpz:u"
      - oauth2_application:
        - "shpz:u"
  /shop:
    get:
      tags:
      - "shop"
      summary: "Get Shop"
      description: ""
      operationId: "merchant-shop-get"
    patch:
      tags:
      - "shop"
      summary: "Update Shop"
      description: ""
      operationId: "merchant-shop-update"
      security:
      - oauth2_accessCode:
        - "shop:u"
      - oauth2_application:
        - "shop:u"
  /shop/address:
    get:
      tags:
      - "shop"
      summary: "Get Merchant Address"
      description: ""
      operationId: "merchant-address-get"
      security:
      - oauth2_accessCode:
        - "shad:r"
      - oauth2_application:
        - "shad:r"
    patch:
      tags:
      - "shop"
      summary: "Update Merchant Address"
      description: ""
      operationId: "merchant-address-jsonpatch"
      security:
      - oauth2_accessCode:
        - "shad:u"
      - oauth2_application:
        - "shad:u"
  /shop/attributes:
    get:
      tags:
      - "shop"
      summary: "List Merchant Shop Attributes"
      description: ""
      operationId: "merchant-shop-attribute-get-list"
      security:
      - oauth2_accessCode:
        - "shat:r"
      - oauth2_application:
        - "shat:r"
    post:
      tags:
      - "shop"
      summary: "Create Merchant Shop Attribute"
      description: ""
      operationId: "merchant-shop-attribute-create"
      security:
      - oauth2_accessCode:
        - "shat:c"
      - oauth2_application:
        - "shat:c"
  /shop/close:
    post:
      tags:
      - "shop"
      summary: "Close Shop"
      description: ""
      operationId: "merchant-shop-close"
      security:
      - oauth2_accessCode:
        - "shcl:c"
      - oauth2_application:
        - "shcl:c"
  /shop/features:
    get:
      tags:
      - "shop"
      summary: "List Shop Features"
      description: ""
      operationId: "shop-feature-get-list"
      security:
      - oauth2_accessCode:
        - "feat:r"
      - oauth2_application:
        - "feat:r"
  /shop/images:
    get:
      tags:
      - "shop"
      summary: "/shop/images"
      description: ""
      operationId: "merchant-images-list"
    post:
      tags:
      - "shop"
      summary: "Create Image"
      description: ""
      operationId: "merchant-images-create"
      security:
      - oauth2_accessCode:
        - "shim:c"
      - oauth2_application:
        - "shim:c"
  /shop/legal:
    get:
      tags:
      - "shop"
      summary: "Shop legal details"
      description: ""
      operationId: "merchant-legal-get"
      security:
      - oauth2_accessCode:
        - "legl:r"
      - oauth2_application:
        - "legl:r"
    patch:
      tags:
      - "shop"
      summary: "Update Legal Resource"
      description: ""
      operationId: "merchant-legal-jsonpatch"
      security:
      - oauth2_accessCode:
        - "legl:u"
      - oauth2_application:
        - "legl:u"
  /shop/open:
    post:
      tags:
      - "shop"
      summary: "Open Shop"
      description: ""
      operationId: "merchant-shop-open"
      security:
      - oauth2_accessCode:
        - "shcl:c"
      - oauth2_application:
        - "shcl:c"
  /shop/attributes/{name}:
    get:
      tags:
      - "shop"
      summary: "Get Merchant Shop Attribute"
      description: ""
      operationId: "merchant-shop-attribute-get"
      security:
      - oauth2_accessCode:
        - "shat:r"
      - oauth2_application:
        - "shat:r"
    put:
      tags:
      - "shop"
      summary: "Update Merchant Shop Attribute"
      description: ""
      operationId: "merchant-shop-attribute-update"
      security:
      - oauth2_accessCode:
        - "shat:u"
      - oauth2_application:
        - "shat:u"
    delete:
      tags:
      - "shop"
      summary: "/shop/attributes/{name}"
      description: ""
      operationId: "merchant-shop-attribute-delete"
      security:
      - oauth2_accessCode:
        - "shat:d"
      - oauth2_application:
        - "shat:d"
  /shop/features/{featureName}:
    get:
      tags:
      - "shop"
      summary: "Get Shop Feature"
      description: ""
      operationId: "shop-feature-get"
      security:
      - oauth2_accessCode:
        - "feat:r"
      - oauth2_application:
        - "feat:r"
  /shop/images/{imageId}:
    get:
      tags:
      - "shop"
      summary: "/shop/images/{imageId}"
      description: ""
      operationId: "merchant-image-get"
    delete:
      tags:
      - "shop"
      summary: "Delete Image"
      description: ""
      operationId: "merchant-image-delete"
      security:
      - oauth2_accessCode:
        - "shim:d"
      - oauth2_application:
        - "shim:d"
  /shop/images/search/find-by-label:
    get:
      tags:
      - "shop"
      summary: "/shop/images/search/find-by-label"
      description: ""
      operationId: "merchant-images-search-find-by-label"
  /shop-id:
    get:
      tags:
      - "shop-id"
      summary: "Get Shop Id"
      description: ""
      operationId: "shop-id-get"
      security:
      - oauth2_accessCode:
        - "paym:m"
      - oauth2_application:
        - "paym:m"
  /shops/{id}/attributes/{name}:
    delete:
      tags:
      - "shops"
      summary: "/shops/{id}/attributes/{name}"
      description: ""
      operationId: "system-attribute-delete"
      security:
      - oauth2_accessCode:
        - "shat:d"
      - oauth2_application:
        - "shat:d"
  /signers:
    get:
      tags:
      - "signers"
      summary: "Get Signer"
      description: ""
      operationId: "signers-get"
    post:
      tags:
      - "signers"
      summary: "Update Signer"
      description: ""
      operationId: "signers-create"
  /signers/{id}:
    delete:
      tags:
      - "signers"
      summary: "Delete Signer"
      description: ""
      operationId: "signers-delete"
  /users:
    get:
      tags:
      - "users"
      summary: "List Users"
      description: ""
      operationId: "users-list"
      security:
      - oauth2_accessCode:
        - "user:r"
      - oauth2_application:
        - "user:r"
    post:
      tags:
      - "users"
      summary: "Create User"
      description: ""
      operationId: "users-create"
      security:
      - oauth2_accessCode:
        - "user:c"
      - oauth2_application:
        - "user:c"
  /users/reset-password-request:
    post:
      tags:
      - "users"
      summary: "Trigger User Password Reset"
      description: ""
      operationId: "reset-password-request"
  /users/search:
    get:
      tags:
      - "users"
      summary: "Search Users"
      description: ""
      operationId: "users-search"
      security:
      - oauth2_accessCode:
        - "user:r"
      - oauth2_application:
        - "user:r"
  /users/support:
    get:
      tags:
      - "users"
      summary: "Get Support Access Status"
      description: ""
      operationId: "support-access-status"
      security:
      - oauth2_accessCode:
        - "user:r"
      - oauth2_application:
        - "user:r"
    post:
      tags:
      - "users"
      summary: "Enable Support Access"
      description: ""
      operationId: "enable-support-access"
      security:
      - oauth2_accessCode:
        - "user:c"
      - oauth2_application:
        - "user:c"
    delete:
      tags:
      - "users"
      summary: "Disable Support Access"
      description: ""
      operationId: "disable-support-access"
      security:
      - oauth2_accessCode:
        - "user:d"
      - oauth2_application:
        - "user:d"
  /users/verify-password:
    post:
      tags:
      - "users"
      summary: "Verify Password"
      description: ""
      operationId: "verify-password"
  /users/{id}:
    get:
      tags:
      - "users"
      summary: "Get User"
      description: ""
      operationId: "user-get"
      security:
      - oauth2_accessCode:
        - "user:r"
      - oauth2_application:
        - "user:r"
  /users/search/find-by-username:
    get:
      tags:
      - "users"
      summary: "Find User by Username"
      description: ""
      operationId: "users-search-find-by-username"
      security:
      - oauth2_accessCode:
        - "user:r"
      - oauth2_application:
        - "user:r"
  /users/{id}/change-email-request:
    post:
      tags:
      - "users"
      summary: "Trigger User Email Change"
      description: ""
      operationId: "change-email-request"
  /users/{id}/change-password:
    post:
      tags:
      - "users"
      summary: "Change User Password"
      description: ""
      operationId: "user-change-password"
  /users/{id}/change-username:
    post:
      tags:
      - "users"
      summary: "Change User Username"
      description: ""
      operationId: "user-change-username"
  /users/{id}/roles:
    get:
      tags:
      - "users"
      summary: "List User Roles"
      description: ""
      operationId: "user-roles-list"
      security:
      - oauth2_accessCode:
        - "user:r"
      - oauth2_application:
        - "user:r"
    post:
      tags:
      - "users"
      summary: "Add User Role"
      description: ""
      operationId: "user-roles-add"
      security:
      - oauth2_accessCode:
        - "user:r"
        - "user:u"
      - oauth2_application:
        - "user:r"
        - "user:u"
    put:
      tags:
      - "users"
      summary: "Set User Roles"
      description: ""
      operationId: "user-roles-set"
      security:
      - oauth2_accessCode:
        - "user:u"
      - oauth2_application:
        - "user:u"
  /webhook-subscriptions:
    get:
      tags:
      - "webhook-subscriptions"
      summary: "List Subscription"
      description: ""
      operationId: "subscriptions-list"
    post:
      tags:
      - "webhook-subscriptions"
      summary: "Create Subscription"
      description: ""
      operationId: "subscription-create"
      security:
      - oauth2_accessCode:
        - "ordr:r"
        - "prod:r"
      - oauth2_application:
        - "ordr:r"
        - "prod:r"
  /webhook-subscriptions/{id}:
    get:
      tags:
      - "webhook-subscriptions"
      summary: "Get Subscription"
      description: ""
      operationId: "subscription-get"
    put:
      tags:
      - "webhook-subscriptions"
      summary: "Update Subscription"
      description: ""
      operationId: "subscription-update"
      security:
      - oauth2_accessCode:
        - "ordr:r"
        - "prod:r"
      - oauth2_application:
        - "ordr:r"
        - "prod:r"
    delete:
      tags:
      - "webhook-subscriptions"
      summary: "Delete Subscription"
      description: ""
      operationId: "subscription-delete"
  /webhook-subscriptions/{id}/activate:
    post:
      tags:
      - "webhook-subscriptions"
      summary: "Activate Subscription"
      description: ""
      operationId: "subscription-activate"
  /webhook-subscriptions/{id}/deactivate:
    post:
      tags:
      - "webhook-subscriptions"
      summary: "Deactivate Subscription"
      description: ""
      operationId: "subscription-deactivate"
securityDefinitions:
  oauth2_accessCode:
    type: "oauth2"
    authorizationUrl: "https://api-shop.beyondshop.cloud/api/auth/oauth-ext/authorize"
    tokenUrl: "https://api-shop.beyondshop.cloud/api/oauth/token"
    flow: "accessCode"
    scopes:
      adon:r: "No description"
      adon:m: "No description"
      catg:r: "No description"
      catg:c: "No description"
      catg:u: "No description"
      catg:d: "No description"
      cset:r: "No description"
      cset:u: "No description"
      invn:r: "No description"
      invn:u: "No description"
      ordn:r: "No description"
      ordn:u: "No description"
      gsad:r: "No description"
      gsad:u: "No description"
      gsad:c: "No description"
      gsad:d: "No description"
      gspr:r: "No description"
      gspr:c: "No description"
      gspr:u: "No description"
      gspr:d: "No description"
      lcnt:u: "No description"
      ordr:r: "No description"
      ordr:u: "No description"
      orde:r: "No description"
      ordp:r: "No description"
      rfpr:r: "No description"
      rtpr:r: "No description"
      rtpr:c: "No description"
      shpr:r: "No description"
      shpr:c: "No description"
      rfpr:u: "No description"
      shpr:u: "No description"
      pymt:r: "No description"
      pymt:u: "No description"
      pymt:c: "No description"
      pymt:d: "No description"
      pymi:m: "No description"
      paym:m: "Integrate a payment solution"
      papp:m: "No description"
      prad:r: "No description"
      prad:c: "No description"
      prad:d: "No description"
      prad:u: "No description"
      prst:r: "No description"
      prst:u: "No description"
      prod:r: "No description"
      prod:c: "No description"
      prod:d: "No description"
      prod:u: "No description"
      prda:r: "No description"
      prda:u: "No description"
      scop:r: "No description"
      shpz:r: "No description"
      shpz:u: "No description"
      shpz:c: "No description"
      shpz:d: "No description"
      shop:u: "No description"
      shad:r: "No description"
      shad:u: "No description"
      shat:r: "No description"
      shat:c: "No description"
      shcl:c: "No description"
      feat:r: "No description"
      shim:c: "No description"
      legl:r: "No description"
      legl:u: "No description"
      shat:u: "No description"
      shat:d: "No description"
      shim:d: "No description"
      user:r: "No description"
      user:c: "No description"
      user:d: "No description"
      user:u: "No description"
  oauth2_application:
    type: "oauth2"
    tokenUrl: "https://api-shop.beyondshop.cloud/api/oauth/token"
    flow: "application"
    scopes:
      adon:r: "No description"
      adon:m: "No description"
      catg:r: "No description"
      catg:c: "No description"
      catg:u: "No description"
      catg:d: "No description"
      cset:r: "No description"
      cset:u: "No description"
      invn:r: "No description"
      invn:u: "No description"
      ordn:r: "No description"
      ordn:u: "No description"
      gsad:r: "No description"
      gsad:u: "No description"
      gsad:c: "No description"
      gsad:d: "No description"
      gspr:r: "No description"
      gspr:c: "No description"
      gspr:u: "No description"
      gspr:d: "No description"
      lcnt:u: "No description"
      ordr:r: "No description"
      ordr:u: "No description"
      orde:r: "No description"
      ordp:r: "No description"
      rfpr:r: "No description"
      rtpr:r: "No description"
      rtpr:c: "No description"
      shpr:r: "No description"
      shpr:c: "No description"
      rfpr:u: "No description"
      shpr:u: "No description"
      pymt:r: "No description"
      pymt:u: "No description"
      pymt:c: "No description"
      pymt:d: "No description"
      pymi:m: "No description"
      paym:m: "Integrate a payment solution"
      papp:m: "No description"
      prad:r: "No description"
      prad:c: "No description"
      prad:d: "No description"
      prad:u: "No description"
      prst:r: "No description"
      prst:u: "No description"
      prod:r: "No description"
      prod:c: "No description"
      prod:d: "No description"
      prod:u: "No description"
      prda:r: "No description"
      prda:u: "No description"
      scop:r: "No description"
      shpz:r: "No description"
      shpz:u: "No description"
      shpz:c: "No description"
      shpz:d: "No description"
      shop:u: "No description"
      shad:r: "No description"
      shad:u: "No description"
      shat:r: "No description"
      shat:c: "No description"
      shcl:c: "No description"
      feat:r: "No description"
      shim:c: "No description"
      legl:r: "No description"
      legl:u: "No description"
      shat:u: "No description"
      shat:d: "No description"
      shim:d: "No description"
      user:r: "No description"
      user:c: "No description"
      user:d: "No description"
      user:u: "No description"
  basic:
    type: "basic"