swagger: "2.0"
info:
  version: 1.0.0
  title: Beyond REST API
host: api-shop.beyondshop.cloud
basePath: /api
schemes:
- https
paths:
  /:
    get:
      summary: Index unauthorized
      description: ""
      operationId: index-unauthorized
  /carts:
    post:
      tags:
      - carts
      summary: Create cart
      description: Creates a cart.
      operationId: cart-create
  /carts/{cartId}:
    get:
      tags:
      - carts
      summary: Show cart details
      description: Returns the details of the cart identified by {cartId}.
      operationId: cart-get
    delete:
      tags:
      - carts
      summary: Delete cart
      description: Deletes the cart identified by {cartId}.
      operationId: cart-delete
  /carts/{cartId}/billing-address:
    put:
      tags:
      - carts
      summary: Set cart billing address
      description: Sets the billing address of the cart identified by {cartId}. The
        billing address is mandatory for a cart being ready to order.
      operationId: cart-set-billing-address
  /carts/{cartId}/create-payment:
    post:
      tags:
      - carts
      summary: Create payment
      description: Creates a payment for the cart identified by {cartId}.
      operationId: cart-create-payment
  /carts/{cartId}/create-payment-and-order:
    post:
      tags:
      - carts
      summary: Create payment and order
      description: If the payment method's flow is `PAYMENT_ON_BUY`, initiates payment
        and order for the cart identified by {cartId} with a single request. Not possible
        with `PAYMENT_ON_SELECTION`.
      operationId: cart-create-payment-and-order
  /carts/{cartId}/line-items:
    post:
      tags:
      - carts
      summary: Add single line item to cart
      description: Adds a line item to the cart identified by {cartId}. Currently
        only product line items are supported.
      operationId: cart-add-line-item
    put:
      tags:
      - carts
      summary: Set line items
      description: Adds line items to the cart identified by {cartId}. Currently only
        product line items are supported.
      operationId: cart-set-line-items
  /carts/{cartId}/order:
    post:
      tags:
      - carts
      summary: Create order from cart
      description: |-
        Creates an order from the cart identified by {cartId}.

        This endpoint can only be used on a cart with `checkoutState.readyToOrder == true`. The `readyToOrder` does not include the availability check, so this might still fail if stock-managed products are not available.

        The response contains a location header with a link to the order. Note that the order is created asynchronously and is not available immediately.
      operationId: cart-order
  /carts/{cartId}/payment-methods:
    get:
      tags:
      - carts
      summary: List payment methods of cart
      description: |-
        Returns a list of the applicable payment methods of the cart identified by {cartId}. The payment method type is documented [here](https://beyond-rest-api.docs.stoplight.io/beyond-rest-api/api-reference/payment-methods/payment-method-percentage-get).

        The `selectable` field indicates if a payment method is currently selectable. Non-selectable payment methods are currently restricted because of rules that apply to a cart. Trying to set such a payment method as the current one of the cart will fail.
      operationId: cart-get-payment-methods
  /carts/{cartId}/shipping-address:
    put:
      tags:
      - carts
      summary: Set current cart shipping address
      description: Sets the shipping address of the cart identified by {cartId}. If
        a shipping address is not set, it will default to the billing address.
      operationId: cart-set-shipping-address
    delete:
      tags:
      - carts
      summary: Delete shipping address
      description: Deletes the shipping address of the cart identified by {cartId}.
        After deletion, the shipping address will default to the billing address.
      operationId: cart-remove-shipping-address
  /carts/{cartId}/shipping-methods:
    get:
      tags:
      - carts
      summary: Show applicable cart shipping method details
      description: |-
        Returns the applicable shipping method of the cart identified by {cartId}.

        The `selectable` field indicates if a shipping method is currently selectable. Non-selectable shipping methods are currently restricted because of rules that apply to a cart. Trying to set such a shipping method as the current one of the cart will fail.
      operationId: cart-get-shipping-methods
  /carts/{cartId}/line-items/{lineItemId}:
    put:
      tags:
      - carts
      summary: Replace single line item
      description: Replaces only one line item in the cart identified by {cartId}.
      operationId: cart-replace-line-item
    delete:
      tags:
      - carts
      summary: Delete line item
      description: Deletes the line item identified by {lineItemId} from the cart
        identified by {cartId}.
      operationId: cart-delete-line-item
  /carts/{cartId}/payment-methods/current:
    get:
      tags:
      - carts
      summary: Show current cart payment method details
      description: Returns the current payment method of the cart identified by {cartId}.
        The payment method type is documented [here](https://beyond-rest-api.docs.stoplight.io/beyond-rest-api/api-reference/payment-methods/payment-method-percentage-get).
      operationId: cart-get-payment-methods-current
    put:
      tags:
      - carts
      summary: Set current cart payment method
      description: Sets the current payment method of the cart identified by {cartId}.
      operationId: cart-set-payment-methods-current
  /carts/{cartId}/payment-methods/default:
    put:
      tags:
      - carts
      summary: Set cart payment method to current default
      description: Sets the payment method of the cart identified by {cartId} to the
        current default payment method. The default payment method is the one with
        the highest priority of the applicable payment methods.
      operationId: cart-set-payment-methods-default
  /carts/{cartId}/shipping-methods/current:
    get:
      tags:
      - carts
      summary: Show current cart shipping method details
      description: Shows details for the current shipping method of the cart identified
        by {cartId}.
      operationId: cart-get-shipping-methods-current
    put:
      tags:
      - carts
      summary: Set current cart shipping method
      description: Sets the current shipping method of the cart identified by {cartId}.
      operationId: cart-set-shipping-methods-current
  /carts/{cartId}/shipping-methods/default:
    put:
      tags:
      - carts
      summary: Set cart shipping method to current default
      description: Sets the shipping method of the cart identified by {cartId} to
        the current default shipping method. The default shipping method is the one
        with the highest priority of the applicable shipping methods.
      operationId: cart-set-shipping-methods-default
  /categories:
    get:
      tags:
      - categories
      summary: List Categories
      description: ""
      operationId: categories-list
      security:
      - oauth2_accessCode:
        - catg:r
      - oauth2_application:
        - catg:r
    post:
      tags:
      - categories
      summary: Create Category
      description: ""
      operationId: category-create
      security:
      - oauth2_accessCode:
        - catg:c
      - oauth2_application:
        - catg:c
  /categories/{id}:
    get:
      tags:
      - categories
      summary: Get Category
      description: ""
      operationId: category-get
      security:
      - oauth2_accessCode:
        - catg:r
      - oauth2_application:
        - catg:r
    put:
      tags:
      - categories
      summary: Update Category
      description: ""
      operationId: category-put
      security:
      - oauth2_accessCode:
        - catg:u
      - oauth2_application:
        - catg:u
    delete:
      tags:
      - categories
      summary: Delete Category
      description: ""
      operationId: category-delete
      security:
      - oauth2_accessCode:
        - catg:d
      - oauth2_application:
        - catg:d
    patch:
      tags:
      - categories
      summary: Update Category
      description: ""
      operationId: category-patch-jsonpatch
      security:
      - oauth2_accessCode:
        - catg:u
      - oauth2_application:
        - catg:u
  /checkout-settings:
    get:
      tags:
      - checkout-settings
      summary: List checkout settings
      description: Returns the checkout settings of the current shop.
      operationId: checkout-settings-get
      security:
      - oauth2_accessCode:
        - cset:r
      - oauth2_application:
        - cset:r
    put:
      tags:
      - checkout-settings
      summary: Update checkout settings
      description: Updates the checkout settings of the current shop.
      operationId: checkout-settings-update
      security:
      - oauth2_accessCode:
        - cset:u
      - oauth2_application:
        - cset:u
  /configuration/invoice-number:
    get:
      tags:
      - configuration
      summary: Show invoice number configuration details
      description: Returns the invoice number configuration for the current shop.
      operationId: invoice-number-get
      security:
      - oauth2_accessCode:
        - invn:r
      - oauth2_application:
        - invn:r
    put:
      tags:
      - configuration
      summary: Modify complete invoice number configuration
      description: Modifies the complete invoice number configuration for the current
        shop.
      operationId: invoice-number-put
      security:
      - oauth2_accessCode:
        - invn:u
      - oauth2_application:
        - invn:u
    patch:
      tags:
      - configuration
      summary: Update invoice number configuration partially (JSON)
      description: |-
        Updates parts of the invoice number configuration for the current shop.

        The patch can alternatively be applied using the `application/json-patch` content type.
      operationId: invoice-number-patch
      security:
      - oauth2_accessCode:
        - invn:u
      - oauth2_application:
        - invn:u
  /configuration/order-number:
    get:
      tags:
      - configuration
      summary: Show order number configuration details
      description: Returns the order number configuration for the current shop.
      operationId: order-number-get
      security:
      - oauth2_accessCode:
        - ordn:r
      - oauth2_application:
        - ordn:r
    put:
      tags:
      - configuration
      summary: Modify complete order number configuration
      description: Modifies the complete order number configuration for the current
        shop.
      operationId: order-number-put
      security:
      - oauth2_accessCode:
        - ordn:u
      - oauth2_application:
        - ordn:u
    patch:
      tags:
      - configuration
      summary: Update order number configuration partially (JSON)
      description: |-
        Updates parts of the order number configuration for the current shop.

        The patch can alternatively be applied using the `application/json-patch` content type.
      operationId: order-number-patch
      security:
      - oauth2_accessCode:
        - ordn:u
      - oauth2_application:
        - ordn:u
  /legal-content:
    get:
      tags:
      - legal-content
      summary: List Legal Content
      description: ""
      operationId: merchant-legal-content-list
  /legal-content/{name}:
    get:
      tags:
      - legal-content
      summary: Get Legal Content
      description: ""
      operationId: merchant-legal-content-get
    put:
      tags:
      - legal-content
      summary: Update Legal Content
      description: ""
      operationId: merchant-legal-content-edit
      security:
      - oauth2_accessCode:
        - lcnt:u
      - oauth2_application:
        - lcnt:u
  /oauth/token:
    post:
      tags:
      - oauth
      summary: Create a JSON Web Token with a refresh token
      description: |-
        Creates a JSON Web Token which is valid for 12 hours for the current shop. The other available flows are `client_credentials` and `authorization_code`.
        The token grants access to all resources which correspond to the scopes the respective client has.
      operationId: oauth2-token-refresh
      security:
      - basic: []
  /orders:
    get:
      tags:
      - orders
      summary: List orders
      description: Returns a list of all orders of the current shop in a paged way.
        Each item in the response represents the order's details.
      operationId: orders-list
      security:
      - oauth2_accessCode:
        - ordr:r
      - oauth2_application:
        - ordr:r
  /orders/{order-id}:
    get:
      tags:
      - orders
      summary: Show order details
      description: Returns the details of an order.
      operationId: order-get
      security:
      - oauth2_accessCode:
        - ordr:r
      - oauth2_application:
        - ordr:r
  /orders/search/find-by-cart-id:
    get:
      tags:
      - orders
      summary: Show order by cart ID
      description: Returns the details of an order by the `cartId` passed as a request
        parameter.
      operationId: order-get-by-cartid
      security:
      - oauth2_accessCode:
        - ordr:r
      - oauth2_application:
        - ordr:r
  /orders/{id}/send-invoice:
    post:
      tags:
      - orders
      summary: Send invoice
      description: Sends an invoice for the order identified by {orderId}.
      operationId: order-send-invoice
      security:
      - oauth2_accessCode:
        - ordr:u
      - oauth2_application:
        - ordr:u
  /orders/{order-id}/billing-address:
    put:
      tags:
      - orders
      summary: Update billing address
      description: Updates the customer’s billing address.
      operationId: order-update-billing-address
      security:
      - oauth2_accessCode:
        - ordr:u
      - oauth2_application:
        - ordr:u
  /orders/{order-id}/create-invoice:
    post:
      tags:
      - orders
      summary: Create invoice
      description: Creates an invoice for the order identified by {orderId}.
      operationId: order-create-invoice
      security:
      - oauth2_accessCode:
        - ordr:u
      - oauth2_application:
        - ordr:u
  /orders/{order-id}/events:
    get:
      tags:
      - orders
      summary: List order events
      description: Returns a list of all events of the order identified by {orderId}
        in a paged way.
      operationId: order-events-list
      security:
      - oauth2_accessCode:
        - orde:r
      - oauth2_application:
        - orde:r
  /orders/{order-id}/order-note:
    put:
      tags:
      - orders
      summary: Update order note
      description: Updates the order note of the order identified by {orderId}.
      operationId: order-note-update
      security:
      - oauth2_accessCode:
        - ordr:u
      - oauth2_application:
        - ordr:u
  /orders/{order-id}/processes:
    get:
      tags:
      - orders
      summary: List order processes
      description: Returns a list of all order processes for the order identified
        by {orderId}.
      operationId: get-order-processes
      security:
      - oauth2_accessCode:
        - ordp:r
      - oauth2_application:
        - ordp:r
  /orders/{order-id}/shipping-address:
    put:
      tags:
      - orders
      summary: Update shipping address
      description: Updates the customer’s shipping address.
      operationId: order-update-shipping-address
      security:
      - oauth2_accessCode:
        - ordr:u
      - oauth2_application:
        - ordr:u
  /orders/{order-id}/processes/refunds:
    get:
      tags:
      - orders
      summary: List refund processes
      description: Returns a list of all refund processes of an order in a paged way.
        Refunds are triggered if either a cancelation or return process is created.
        See "Create cancelation processes" and ["Create return processes"](https://beyond-rest-api.docs.stoplight.io/beyond-rest-api/api-reference/orders/create-return-process)
        for more information.
      operationId: get-refund-processes
      security:
      - oauth2_accessCode:
        - rfpr:r
      - oauth2_application:
        - rfpr:r
  /orders/{order-id}/processes/returns:
    get:
      tags:
      - orders
      summary: List return processes
      description: Returns a list of all return processes of the order identified
        by {orderId} in a paged way.
      operationId: get-return-processes
      security:
      - oauth2_accessCode:
        - rtpr:r
      - oauth2_application:
        - rtpr:r
    post:
      tags:
      - orders
      summary: Create return process
      description: Creates a new return process for the order identified by {orderId}.
        Return processes trigger a refund process.
      operationId: create-return-process
      security:
      - oauth2_accessCode:
        - rtpr:c
      - oauth2_application:
        - rtpr:c
  /orders/{order-id}/processes/shippings:
    get:
      tags:
      - orders
      summary: List shipping processes
      description: Returns a list of all shipping processes of the order identified
        by {orderId} in a paged way.
      operationId: get-shipping-processes
      security:
      - oauth2_accessCode:
        - shpr:r
      - oauth2_application:
        - shpr:r
    post:
      tags:
      - orders
      summary: Create shipping process
      description: Creates a shipping process for the order identified by {orderId}.
      operationId: create-shipping-process
      security:
      - oauth2_accessCode:
        - shpr:c
      - oauth2_application:
        - shpr:c
  /orders/{order-id}/processes/refunds/active:
    get:
      tags:
      - orders
      summary: Show active refund process details
      description: Returns details for the active refund process. There is only one
        active refund process at a time. For more information about the request and
        response structure see ["Show refund process details"](https://beyond-rest-api.docs.stoplight.io/beyond-rest-api/api-reference/orders/get-refund-process).
      operationId: get-active-refund-process
      security:
      - oauth2_accessCode:
        - rfpr:r
      - oauth2_application:
        - rfpr:r
  /orders/{order-id}/processes/refunds/{id}:
    get:
      tags:
      - orders
      summary: Show refund process details
      description: Returns the details for the refund process identified by {refundProcessId}.
      operationId: get-refund-process
      security:
      - oauth2_accessCode:
        - rfpr:r
      - oauth2_application:
        - rfpr:r
  /orders/{order-id}/processes/returns/{return-process-id}:
    get:
      tags:
      - orders
      summary: Show return process details
      description: Returns details for the return process identified by {returnProcessId}
        in the order identified by {orderId}.
      operationId: get-return-process
      security:
      - oauth2_accessCode:
        - rtpr:r
      - oauth2_application:
        - rtpr:r
  /orders/{order-id}/processes/shippings/{shipping-process-id}:
    get:
      tags:
      - orders
      summary: Show shipping process details
      description: Returns the shipping process details for the shipment identified
        by {shippingProcessId} in the order identified by {orderId}.
      operationId: get-shipping-process
      security:
      - oauth2_accessCode:
        - shpr:r
      - oauth2_application:
        - shpr:r
  /orders/{order-id}/processes/refunds/active/mark-paid:
    post:
      tags:
      - orders
      summary: Mark refund process as paid
      description: Marks the active refund process for the order identified by {orderId}
        as paid.
      operationId: mark-refund-process-paid
      security:
      - oauth2_accessCode:
        - rfpr:u
      - oauth2_application:
        - rfpr:u
  /orders/{order-id}/processes/shippings/{shipping-process-id}/mark-delivered:
    post:
      tags:
      - orders
      summary: Mark shipment as delivered
      description: Marks the shipment identified by {shippingProcessId} in the order
        identified by {orderId} as delivered.
      operationId: mark-shipping-process-delivered
      security:
      - oauth2_accessCode:
        - shpr:u
      - oauth2_application:
        - shpr:u
  /orders/{order-id}/processes/shippings/{shipping-process-id}/mark-shipped:
    post:
      tags:
      - orders
      summary: Mark shipment as shipped
      description: Marks the shipment identified by {shippingProcessId} in the order
        identified by {orderId} as shipped.
      operationId: mark-shipping-process-shipped
      security:
      - oauth2_accessCode:
        - shpr:u
      - oauth2_application:
        - shpr:u
  /payment-method-definitions:
    get:
      tags:
      - payment-method-definitions
      summary: List payment method definitions
      description: ""
      operationId: list-payment-method-definition
      security:
      - oauth2_accessCode:
        - paym:m
      - oauth2_application:
        - paym:m
    post:
      tags:
      - payment-method-definitions
      summary: Create payment method definition
      description: ""
      operationId: create-payment-method-definition
      security:
      - oauth2_accessCode:
        - paym:m
      - oauth2_application:
        - paym:m
  /payment-method-definitions/{paymentMethodDefinitionName}:
    get:
      tags:
      - payment-method-definitions
      summary: Get payment method definition
      description: ""
      operationId: get-payment-method-definition
      security:
      - oauth2_accessCode:
        - paym:m
      - oauth2_application:
        - paym:m
    put:
      tags:
      - payment-method-definitions
      summary: Update payment method definition
      description: ""
      operationId: update-payment-method-definition
      security:
      - oauth2_accessCode:
        - paym:m
      - oauth2_application:
        - paym:m
    delete:
      tags:
      - payment-method-definitions
      summary: Delete payment method definition
      description: ""
      operationId: delete-payment-method-definition
      security:
      - oauth2_accessCode:
        - paym:m
      - oauth2_application:
        - paym:m
  /payment-method-definitions/{paymentMethodDefinitionName}/payment-method:
    post:
      tags:
      - payment-method-definitions
      summary: Create payment method
      description: ""
      operationId: create-payment-method
      security:
      - oauth2_accessCode:
        - paym:m
      - oauth2_application:
        - paym:m
    delete:
      tags:
      - payment-method-definitions
      summary: Delete payment method
      description: ""
      operationId: delete-payment-method
      security:
      - oauth2_accessCode:
        - paym:m
      - oauth2_application:
        - paym:m
  /payment-methods:
    get:
      tags:
      - payment-methods
      summary: Show charged payment method details
      description: Returns the details of the charged payment method identified by
        {paymentMethodId}.
      operationId: payment-method-percentage-get
      security:
      - oauth2_accessCode:
        - pymt:r
      - oauth2_application:
        - pymt:r
    post:
      tags:
      - payment-methods
      summary: Create charged payment method
      description: Creates a charged payment method for the current shop.
      operationId: payment-method-percentage-create
      security:
      - oauth2_accessCode:
        - pymt:c
      - oauth2_application:
        - pymt:c
    put:
      tags:
      - payment-methods
      summary: Sort payment methods
      description: Sorts the available payment methods for the current shop.
      operationId: payment-method-sort
      security:
      - oauth2_accessCode:
        - pymt:u
      - oauth2_application:
        - pymt:u
  /payment-methods/{paymentMethodId}:
    get:
      tags:
      - payment-methods
      summary: Show payment method details
      description: Returns the details of the payment method identified by {paymentMethodId}.
      operationId: payment-method-get
      security:
      - oauth2_accessCode:
        - pymt:r
      - oauth2_application:
        - pymt:r
    put:
      tags:
      - payment-methods
      summary: Update payment method
      description: Updates the payment method identified by {paymentMethodId}.
      operationId: payment-method-update
      security:
      - oauth2_accessCode:
        - pymt:u
      - oauth2_application:
        - pymt:u
    delete:
      tags:
      - payment-methods
      summary: Delete payment method
      description: Deletes the payment method identified by {paymentMethodId}.
      operationId: payment-method-delete
      security:
      - oauth2_accessCode:
        - pymt:d
      - oauth2_application:
        - pymt:d
  /payment-methods/{paymentMethodId}/activate:
    post:
      tags:
      - payment-methods
      summary: Activate payment method
      description: Activates the payment method identified by {paymentMethodId}.
      operationId: activate-payment-method
      security:
      - oauth2_accessCode:
        - pymt:u
      - oauth2_application:
        - pymt:u
  /payment-methods/{paymentMethodId}/deactivate:
    post:
      tags:
      - payment-methods
      summary: Deactivate payment method
      description: Deactivates the payment method identified by {paymentMethodId}.
      operationId: deactivate-payment-method
      security:
      - oauth2_accessCode:
        - pymt:u
      - oauth2_application:
        - pymt:u
  /payment-signup/merchant-accounts/{paymentMethodDefinition}:
    get:
      tags:
      - payment-signup
      summary: Get merchant account
      description: ""
      operationId: merchant-account
      security:
      - oauth2_accessCode:
        - pymt:r
      - oauth2_application:
        - pymt:r
    delete:
      tags:
      - payment-signup
      summary: Disconnect merchant account
      description: ""
      operationId: disconnect
      security:
      - oauth2_accessCode:
        - pymt:r
      - oauth2_application:
        - pymt:r
  /payment-signup/referrals/{paymentMethodDefinition}:
    post:
      tags:
      - payment-signup
      summary: Initiate referral
      description: ""
      operationId: referrals
      security:
      - oauth2_accessCode:
        - pymt:r
      - oauth2_application:
        - pymt:r
  /payments/{paymentId}/approve:
    post:
      tags:
      - payments
      summary: Approve payment
      description: ""
      operationId: payment-approve
      security:
      - oauth2_accessCode:
        - paym:m
      - oauth2_application:
        - paym:m
  /payments/{paymentId}/cancel:
    post:
      tags:
      - payments
      summary: Cancel payment
      description: ""
      operationId: payment-cancel
      security:
      - oauth2_accessCode:
        - paym:m
      - oauth2_application:
        - paym:m
  /payments/{paymentId}/fail:
    post:
      tags:
      - payments
      summary: Fail payment
      description: ""
      operationId: payment-fail
      security:
      - oauth2_accessCode:
        - paym:m
      - oauth2_application:
        - paym:m
  /payments/{paymentId}/status:
    post:
      tags:
      - payments
      summary: Set payment status
      description: ""
      operationId: set-payment-status
      security:
      - oauth2_accessCode:
        - paym:m
      - oauth2_application:
        - paym:m
  /product-attribute-definitions:
    get:
      tags:
      - product-attribute-definitions
      summary: List Product Attribute Definitions
      description: ""
      operationId: product-attribute-definitions-list
      security:
      - oauth2_accessCode:
        - prad:r
      - oauth2_application:
        - prad:r
    post:
      tags:
      - product-attribute-definitions
      summary: Create Product Attribute Definition
      description: ""
      operationId: product-attribute-definitions-create-string
      security:
      - oauth2_accessCode:
        - prad:c
      - oauth2_application:
        - prad:c
  /product-attribute-definitions/{productAttributeDefinitionKey}:
    get:
      tags:
      - product-attribute-definitions
      summary: Get Product Attribute Definition
      description: ""
      operationId: product-attribute-definition-get
      security:
      - oauth2_accessCode:
        - prad:r
      - oauth2_application:
        - prad:r
    delete:
      tags:
      - product-attribute-definitions
      summary: Delete Product Attribute Definition
      description: ""
      operationId: product-attribute-definitions-delete
      security:
      - oauth2_accessCode:
        - prad:d
      - oauth2_application:
        - prad:d
  /product-settings:
    get:
      tags:
      - product-settings
      summary: Get Product Settings
      description: ""
      operationId: product-settings-get
      security:
      - oauth2_accessCode:
        - prst:r
      - oauth2_application:
        - prst:r
    patch:
      tags:
      - product-settings
      summary: Update Product Settings
      description: ""
      operationId: product-settings-patch
      security:
      - oauth2_accessCode:
        - prst:u
      - oauth2_application:
        - prst:u
  /product-view/products:
    get:
      tags:
      - product-view
      summary: List Product
      description: ""
      operationId: product-view-list
  /product-view/categories/{categoryId}:
    get:
      tags:
      - product-view
      summary: Get Enchanced View of Category
      description: ""
      operationId: category-get-enhanced
  /product-view/products/{productId}:
    get:
      tags:
      - product-view
      summary: Get Enchanced View of Product
      description: ""
      operationId: product-view-find-by-id-enhanced
  /product-view/categories/search/find-by-label:
    get:
      tags:
      - product-view
      summary: Find Category by Label
      description: ""
      operationId: category-get-by-label
  /product-view/categories/search/find-by-product:
    get:
      tags:
      - product-view
      summary: List Categories Assigned to Product
      description: ""
      operationId: product-view-find-categories-by-product
  /product-view/categories/{categoryId}/products:
    get:
      tags:
      - product-view
      summary: List Products of Category
      description: ""
      operationId: category-products
  /product-view/products/search/find-available-tags:
    get:
      tags:
      - product-view
      summary: 'List Available Tags '
      description: ""
      operationId: product-view-find-available-tags
  /product-view/products/search/find-by-category:
    get:
      tags:
      - product-view
      summary: List Product by Category
      description: ""
      operationId: product-view-find-by-category
  /product-view/products/search/find-by-query:
    post:
      tags:
      - product-view
      summary: List Product by Query
      description: ""
      operationId: product-view-find-by-query
  /product-view/products/search/find-by-search-term:
    get:
      tags:
      - product-view
      summary: List Product by Term
      description: ""
      operationId: product-view-find-by-search-term
  /product-view/products/search/find-by-tags:
    get:
      tags:
      - product-view
      summary: List Product by Tags
      description: ""
      operationId: product-view-find-by-tags
  /products:
    get:
      tags:
      - products
      summary: List Products
      description: ""
      operationId: products-list
      security:
      - oauth2_accessCode:
        - prod:r
      - oauth2_application:
        - prod:r
    post:
      tags:
      - products
      summary: Create Product
      description: ""
      operationId: products-create
      security:
      - oauth2_accessCode:
        - prod:c
      - oauth2_application:
        - prod:c
  /products/{productId}:
    get:
      tags:
      - products
      summary: Get Product
      description: ""
      operationId: product-get
      security:
      - oauth2_accessCode:
        - prod:r
      - oauth2_application:
        - prod:r
    delete:
      tags:
      - products
      summary: Delete Product
      description: ""
      operationId: product-delete
      security:
      - oauth2_accessCode:
        - prod:d
      - oauth2_application:
        - prod:d
    patch:
      tags:
      - products
      summary: Update Product
      description: ""
      operationId: product-patch-json
      security:
      - oauth2_accessCode:
        - prod:u
      - oauth2_application:
        - prod:u
  /products/search/find-by-sku:
    get:
      tags:
      - products
      summary: Find a product by SKU
      description: ""
      operationId: products-search-findBySku
      security:
      - oauth2_accessCode:
        - prod:r
      - oauth2_application:
        - prod:r
  /products/search/tags:
    get:
      tags:
      - products
      summary: Find used tags
      description: ""
      operationId: find-tags-starts-with
      security:
      - oauth2_accessCode:
        - prod:r
      - oauth2_application:
        - prod:r
  /products/{productId}/attachments:
    get:
      tags:
      - products
      summary: List Product Attachments
      description: ""
      operationId: product-attachments-list
      security:
      - oauth2_accessCode:
        - prod:r
      - oauth2_application:
        - prod:r
    post:
      tags:
      - products
      summary: Create Product Attachment
      description: ""
      operationId: product-attachments-create
      security:
      - oauth2_accessCode:
        - prod:u
      - oauth2_application:
        - prod:u
  /products/{productId}/attributes:
    get:
      tags:
      - products
      summary: List Custom Product Attributes
      description: ""
      operationId: product-attributes-list
      security:
      - oauth2_accessCode:
        - prat:r
      - oauth2_application:
        - prat:r
    post:
      tags:
      - products
      summary: Create Custom Product Attribute of type NUMBER with name
      description: ""
      operationId: product-attribute-create-number-with-name
      security:
      - oauth2_accessCode:
        - prat:c
      - oauth2_application:
        - prat:c
  /products/{productId}/availability:
    get:
      tags:
      - products
      summary: Get Product Availability
      description: ""
      operationId: product-availability-get
      security:
      - oauth2_accessCode:
        - prda:r
      - oauth2_application:
        - prda:r
  /products/{productId}/default-image:
    put:
      tags:
      - products
      summary: Set Default Product Image
      description: ""
      operationId: product-images-set-default
      security:
      - oauth2_accessCode:
        - prod:u
      - oauth2_application:
        - prod:u
  /products/{productId}/images:
    get:
      tags:
      - products
      summary: List Product Images
      description: ""
      operationId: product-images-list
      security:
      - oauth2_accessCode:
        - prod:r
      - oauth2_application:
        - prod:r
    post:
      tags:
      - products
      summary: Create Product Image
      description: ""
      operationId: product-images-create
      security:
      - oauth2_accessCode:
        - prod:u
      - oauth2_application:
        - prod:u
  /products/{productId}/attachments/{attachmentId}:
    get:
      tags:
      - products
      summary: Get Product Attachment
      description: ""
      operationId: product-attachment-get
      security:
      - oauth2_accessCode:
        - prod:r
      - oauth2_application:
        - prod:r
    delete:
      tags:
      - products
      summary: Delete Product Attachment
      description: ""
      operationId: product-attachment-delete
      security:
      - oauth2_accessCode:
        - prod:u
      - oauth2_application:
        - prod:u
  /products/{productId}/attributes/{productAttributeName}:
    get:
      tags:
      - products
      summary: Get Product Attribute of type NUMBER
      description: ""
      operationId: product-attribute-get-number
      security:
      - oauth2_accessCode:
        - prat:r
      - oauth2_application:
        - prat:r
    delete:
      tags:
      - products
      summary: Delete Custom Product Attribute
      description: ""
      operationId: product-attribute-delete
      security:
      - oauth2_accessCode:
        - prat:d
      - oauth2_application:
        - prat:d
  /products/{productId}/availability/adjust-available-stock:
    post:
      tags:
      - products
      summary: Adjust Stock Level
      description: ""
      operationId: product-availability-adjust-available-stock
      security:
      - oauth2_accessCode:
        - prda:u
      - oauth2_application:
        - prda:u
  /products/{productId}/availability/disable-purchasability:
    post:
      tags:
      - products
      summary: Disable Purchasability
      description: ""
      operationId: product-availability-disable-purchasability
      security:
      - oauth2_accessCode:
        - prda:u
      - oauth2_application:
        - prda:u
  /products/{productId}/availability/disable-stock-management:
    post:
      tags:
      - products
      summary: Disable Stock Management
      description: ""
      operationId: product-availability-disable-stock-management
      security:
      - oauth2_accessCode:
        - prda:u
      - oauth2_application:
        - prda:u
  /products/{productId}/availability/enable-purchasability:
    post:
      tags:
      - products
      summary: Enable Purchasability
      description: ""
      operationId: product-availability-enable-purchasability
      security:
      - oauth2_accessCode:
        - prda:u
      - oauth2_application:
        - prda:u
  /products/{productId}/availability/enable-stock-management:
    post:
      tags:
      - products
      summary: Enable Stock Management
      description: ""
      operationId: product-availability-enable-stock-management
      security:
      - oauth2_accessCode:
        - prda:u
      - oauth2_application:
        - prda:u
  /products/{productId}/availability/update-stock-threshold:
    post:
      tags:
      - products
      summary: Update Reserve Stock
      description: ""
      operationId: product-availability-update-stock-threshold
      security:
      - oauth2_accessCode:
        - prda:u
      - oauth2_application:
        - prda:u
  /products/{productId}/images/{imageId}:
    get:
      tags:
      - products
      summary: Get Product Image
      description: ""
      operationId: product-image-get
      security:
      - oauth2_accessCode:
        - prod:r
      - oauth2_application:
        - prod:r
    delete:
      tags:
      - products
      summary: Delete Product Image
      description: ""
      operationId: product-image-delete
      security:
      - oauth2_accessCode:
        - prod:u
      - oauth2_application:
        - prod:u
  /scopes:
    get:
      tags:
      - scopes
      summary: List scopes
      description: Returns a list of all scopes in the system for the current shop.
      operationId: scopes-list
      security:
      - oauth2_accessCode:
        - scop:r
      - oauth2_application:
        - scop:r
  /shipping-zones:
    get:
      tags:
      - shipping-zones
      summary: List shipping zones
      description: Returns a list of all shipping zones of the current shop in a paged
        manner.
      operationId: shipping-zones-list
      security:
      - oauth2_accessCode:
        - shpz:r
      - oauth2_application:
        - shpz:r
    post:
      tags:
      - shipping-zones
      summary: Create shipping zone
      description: Creates a shipping zone for the current shop.
      operationId: shipping-zones-create
      security:
      - oauth2_accessCode:
        - shpz:c
      - oauth2_application:
        - shpz:c
    put:
      tags:
      - shipping-zones
      summary: Sort shipping zones
      description: Sorts the shipping zones of the current shop. This is done by passing
        the self-links of the shipping zones in the desired order. The request must
        contain URIs for all shipping zones of the given page.
      operationId: shipping-zones-sort
      security:
      - oauth2_accessCode:
        - shpz:u
      - oauth2_application:
        - shpz:u
  /shipping-zones/{shippingZoneId}:
    get:
      tags:
      - shipping-zones
      summary: Show shipping zone details
      description: Returns the details of the shipping zone identified by {shippingZoneId}.
      operationId: shipping-zone-get
      security:
      - oauth2_accessCode:
        - shpz:r
      - oauth2_application:
        - shpz:r
    put:
      tags:
      - shipping-zones
      summary: Update shipping zone
      description: Updates the shipping zone identified by {shippingZoneId}.
      operationId: shipping-zone-update
      security:
      - oauth2_accessCode:
        - shpz:u
      - oauth2_application:
        - shpz:u
    delete:
      tags:
      - shipping-zones
      summary: Delete shipping zone
      description: Deletes the shipping zone identified by {shippingZoneId}. You cannot
        delete the shipping zone if it is the last one of a shop.
      operationId: shipping-zone-delete
      security:
      - oauth2_accessCode:
        - shpz:d
      - oauth2_application:
        - shpz:d
  /shipping-zones/search/find-all-serviceable-countries:
    get:
      tags:
      - shipping-zones
      summary: Find serviceable countries
      description: Returns a list of the serviceable countries for the current shop.
      operationId: shipping-zones-search-find-serviceable-countries
  /shipping-zones/{shippingZoneId}/shipping-methods:
    get:
      tags:
      - shipping-zones
      summary: Sort shipping methods in shipping zone
      description: Sorts the shipping methods inside the shipping zone identified
        by {shippingZoneId}. This is done by passing the self-links of the shipping
        methods in the desired order. The request must contain URIs for all shipping
        methods of this shipping zone.
      operationId: shipping-zones-shipping-methods-sort
      security:
      - oauth2_accessCode:
        - shpz:r
      - oauth2_application:
        - shpz:r
    post:
      tags:
      - shipping-zones
      summary: Create shipping method
      description: Creates a shipping method with weight-based price in the shipping
        zone identified by {shippingZoneId}.
      operationId: shipping-zones-shipping-methods-create-with-weight-based-price
  /shipping-zones/{shippingZoneId}/shipping-methods/{shippingMethodId}:
    get:
      tags:
      - shipping-zones
      summary: Show weight-based shipping method details in shipping zone
      description: Show the details of the weight-based shipping method identified
        by {shippingMethodId} in the shipping zone identified by {shippingZoneId}.
      operationId: shipping-zones-shipping-method-get-with-weight-based-price
      security:
      - oauth2_accessCode:
        - shpz:r
      - oauth2_application:
        - shpz:r
    put:
      tags:
      - shipping-zones
      summary: Modify shipping method
      description: Modifies the shipping method identified by {shippingMethodId} in
        the shipping zone identified by {shippingZoneId}.
      operationId: shipping-zones-shipping-method-update
      security:
      - oauth2_accessCode:
        - shpz:u
      - oauth2_application:
        - shpz:u
    delete:
      tags:
      - shipping-zones
      summary: Delete shipping method in shipping zone
      description: Deletes the shipping method identified by {shippingMethodId} in
        the shipping zone identified by {shippingZoneId}. You cannot delete the last
        shipping method of a shop.
      operationId: shipping-zones-shipping-method-delete
      security:
      - oauth2_accessCode:
        - shpz:u
      - oauth2_application:
        - shpz:u
  /shop:
    get:
      tags:
      - shop
      summary: Get Shop
      description: ""
      operationId: merchant-shop-get
    patch:
      tags:
      - shop
      summary: Update Shop
      description: ""
      operationId: merchant-shop-update
      security:
      - oauth2_accessCode:
        - shop:u
      - oauth2_application:
        - shop:u
  /shop/address:
    get:
      tags:
      - shop
      summary: Get Merchant Address
      description: ""
      operationId: merchant-address-get
      security:
      - oauth2_accessCode:
        - shad:r
      - oauth2_application:
        - shad:r
    patch:
      tags:
      - shop
      summary: Update Merchant Address
      description: ""
      operationId: merchant-address-jsonpatch
      security:
      - oauth2_accessCode:
        - shad:u
      - oauth2_application:
        - shad:u
  /shop/attributes:
    get:
      tags:
      - shop
      summary: List Merchant Shop Attributes
      description: ""
      operationId: merchant-shop-attribute-get-list
      security:
      - oauth2_accessCode:
        - shat:r
      - oauth2_application:
        - shat:r
    post:
      tags:
      - shop
      summary: Create Merchant Shop Attribute
      description: ""
      operationId: merchant-shop-attribute-create
      security:
      - oauth2_accessCode:
        - shat:c
      - oauth2_application:
        - shat:c
  /shop/close:
    post:
      tags:
      - shop
      summary: Close Shop
      description: ""
      operationId: merchant-shop-close
      security:
      - oauth2_accessCode:
        - shcl:c
      - oauth2_application:
        - shcl:c
  /shop/features:
    get:
      tags:
      - shop
      summary: List Shop Features
      description: ""
      operationId: shop-feature-get-list
      security:
      - oauth2_accessCode:
        - feat:r
      - oauth2_application:
        - feat:r
  /shop/images:
    get:
      tags:
      - shop
      summary: List Shop Images
      description: ""
      operationId: merchant-images-list
    post:
      tags:
      - shop
      summary: Create Image
      description: ""
      operationId: merchant-images-create
      security:
      - oauth2_accessCode:
        - shim:c
      - oauth2_application:
        - shim:c
  /shop/legal:
    get:
      tags:
      - shop
      summary: Shop legal details
      description: ""
      operationId: merchant-legal-get
      security:
      - oauth2_accessCode:
        - legl:r
      - oauth2_application:
        - legl:r
    patch:
      tags:
      - shop
      summary: Update Legal Resource
      description: ""
      operationId: merchant-legal-jsonpatch
      security:
      - oauth2_accessCode:
        - legl:u
      - oauth2_application:
        - legl:u
  /shop/open:
    post:
      tags:
      - shop
      summary: Open Shop
      description: ""
      operationId: merchant-shop-open
      security:
      - oauth2_accessCode:
        - shcl:c
      - oauth2_application:
        - shcl:c
  /shop/attributes/{name}:
    get:
      tags:
      - shop
      summary: Get Merchant Shop Attribute
      description: ""
      operationId: merchant-shop-attribute-get
      security:
      - oauth2_accessCode:
        - shat:r
      - oauth2_application:
        - shat:r
    put:
      tags:
      - shop
      summary: Update Merchant Shop Attribute
      description: ""
      operationId: merchant-shop-attribute-update
      security:
      - oauth2_accessCode:
        - shat:u
      - oauth2_application:
        - shat:u
    delete:
      tags:
      - shop
      summary: Delete Merchant Shop Attribute
      description: ""
      operationId: merchant-shop-attribute-delete
      security:
      - oauth2_accessCode:
        - shat:d
      - oauth2_application:
        - shat:d
  /shop/features/{featureName}:
    get:
      tags:
      - shop
      summary: Get Shop Feature
      description: ""
      operationId: shop-feature-get
      security:
      - oauth2_accessCode:
        - feat:r
      - oauth2_application:
        - feat:r
  /shop/images/{imageId}:
    get:
      tags:
      - shop
      summary: Get Shop Image
      description: ""
      operationId: merchant-image-get
    delete:
      tags:
      - shop
      summary: Delete Image
      description: ""
      operationId: merchant-image-delete
      security:
      - oauth2_accessCode:
        - shim:d
      - oauth2_application:
        - shim:d
  /shop/images/search/find-by-label:
    get:
      tags:
      - shop
      summary: Find Image by Label
      description: ""
      operationId: merchant-images-search-find-by-label
  /shop-id:
    get:
      tags:
      - shop-id
      summary: Get shop ID
      description: ""
      operationId: shop-id-get
      security:
      - oauth2_accessCode:
        - paym:m
      - oauth2_application:
        - paym:m
  /signers:
    get:
      tags:
      - signers
      summary: List signers
      description: Returns a list of all signers for the current shop.
      operationId: signers-get
    post:
      tags:
      - signers
      summary: Create signer
      description: Creates a signer for the current shop.
      operationId: signers-create
  /signers/{id}:
    delete:
      tags:
      - signers
      summary: Delete signer
      description: Deletes the signer identified by {signerId}.
      operationId: signers-delete
  /users:
    get:
      tags:
      - users
      summary: List users
      description: Returns a list of users visible to the current user. This request
        will not list the support user.
      operationId: users-list
      security:
      - oauth2_accessCode:
        - user:r
      - oauth2_application:
        - user:r
    post:
      tags:
      - users
      summary: Create user
      description: Creates a user in the current shop.
      operationId: users-create
      security:
      - oauth2_accessCode:
        - user:c
      - oauth2_application:
        - user:c
  /users/reset-password-request:
    post:
      tags:
      - users
      summary: Trigger password reset email
      description: Triggers a password reset email to be sent to the user identified
        by {userId}. The email will contain a link to the change password settings
        page of the Beyond cockpit. The link includes a JWT to authorize the password
        reset.
      operationId: reset-password-request
  /users/search:
    get:
      tags:
      - users
      summary: List user searches
      description: Returns an overview of the search endpoints the user resource offers.
      operationId: users-search
      security:
      - oauth2_accessCode:
        - user:r
      - oauth2_application:
        - user:r
  /users/support:
    get:
      tags:
      - users
      summary: Retrieve support access status
      description: Returns the status of the support access for a shop, i.e. if the
        support user is enabled or disabled for the shop.
      operationId: support-access-status
      security:
      - oauth2_accessCode:
        - user:r
      - oauth2_application:
        - user:r
    post:
      tags:
      - users
      summary: Enable support access
      description: Enables support access for a shop. If enabled, the customer support
        will receive specific rights for direct support in the Beyond cockpit.
      operationId: enable-support-access
      security:
      - oauth2_accessCode:
        - user:c
      - oauth2_application:
        - user:c
    delete:
      tags:
      - users
      summary: Disable support access
      description: Disables support access for a shop. If enabled, the customer support
        will receive specific rights for direct support in the Beyond cockpit.
      operationId: disable-support-access
      security:
      - oauth2_accessCode:
        - user:d
      - oauth2_application:
        - user:d
  /users/verify-password:
    post:
      tags:
      - users
      summary: Verify password
      description: Verifies a password against the password guidelines.
      operationId: verify-password
  /users/{id}:
    get:
      tags:
      - users
      summary: Show user details
      description: Returns the details of the user identified by {userId}.
      operationId: user-get
      security:
      - oauth2_accessCode:
        - user:r
      - oauth2_application:
        - user:r
  /users/search/find-by-username:
    get:
      tags:
      - users
      summary: Find user by username
      description: Returns a user by the username passed as a request parameter.
      operationId: users-search-find-by-username
      security:
      - oauth2_accessCode:
        - user:r
      - oauth2_application:
        - user:r
  /users/{id}/change-email-request:
    post:
      tags:
      - users
      summary: Trigger email address change
      description: Triggers an email address change. A confirmation email to change
        the email address will be sent to the user. The confirmation email will contain
        a link to the email address change page of the Beyond cockpit. The link includes
        a JWT to authorize the email address change.
      operationId: change-email-request
  /users/{id}/change-password:
    post:
      tags:
      - users
      summary: Change password
      description: Changes the password of the user identified by {userId}.
      operationId: user-change-password
  /users/{id}/change-username:
    post:
      tags:
      - users
      summary: Change username
      description: Changes the username of the user identified by {userId}.
      operationId: user-change-username
  /users/{id}/roles:
    get:
      tags:
      - users
      summary: List user roles
      description: Returns a list of all roles of the user identified by {userId}.
      operationId: user-roles-list
      security:
      - oauth2_accessCode:
        - user:r
      - oauth2_application:
        - user:r
    post:
      tags:
      - users
      summary: Add user roles
      description: Adds roles to the user identified by {userId}.
      operationId: user-roles-add
      security:
      - oauth2_accessCode:
        - user:r
        - user:u
      - oauth2_application:
        - user:r
        - user:u
    put:
      tags:
      - users
      summary: Set user roles
      description: Sets the roles of the user identified by {userId}.
      operationId: user-roles-set
      security:
      - oauth2_accessCode:
        - user:u
      - oauth2_application:
        - user:u
  /webhook-subscriptions:
    get:
      tags:
      - webhook-subscriptions
      summary: List webhook subscriptions
      description: Returns a list of all of the webhook subscriptions for the current
        shop in a paged way.
      operationId: subscriptions-list
    post:
      tags:
      - webhook-subscriptions
      summary: Create webhook subscription
      description: |-
        Creates a webhook subscription.

        The scopes needed for the operation depend on the event types you register for, e.g. order events require the scope `orde:r`.
      operationId: subscription-create
      security:
      - oauth2_accessCode:
        - ordr:r
        - prod:r
      - oauth2_application:
        - ordr:r
        - prod:r
  /webhook-subscriptions/{id}:
    get:
      tags:
      - webhook-subscriptions
      summary: Show webhook subscription details
      description: Returns the details of the webhook subscription identified by {webhookSubscriptionId}.
      operationId: subscription-get
    put:
      tags:
      - webhook-subscriptions
      summary: Update webhook subscription
      description: |-
        Updates a webhook subscription.

        The scopes needed for the operation depend on the event types you register for, e.g. order events require the scope `orde:r`.
      operationId: subscription-update
      security:
      - oauth2_accessCode:
        - ordr:r
        - prod:r
      - oauth2_application:
        - ordr:r
        - prod:r
    delete:
      tags:
      - webhook-subscriptions
      summary: Delete webhook subscription
      description: Deletes the webhook subscription identified by {webhookSubscriptionId}.
      operationId: subscription-delete
  /webhook-subscriptions/{id}/activate:
    post:
      tags:
      - webhook-subscriptions
      summary: Activate webhook subscription
      description: Activates the webhook subscription identified by {webhookSubscriptionId}.
      operationId: subscription-activate
  /webhook-subscriptions/{id}/deactivate:
    post:
      tags:
      - webhook-subscriptions
      summary: Deactivate webhook subscription
      description: Deactivates the webhook subscription identified by {webhookSubscriptionId}.
      operationId: subscription-deactivate
securityDefinitions:
  oauth2_accessCode:
    type: oauth2
    authorizationUrl: https://api-shop.beyondshop.cloud/api/auth/oauth-ext/authorize
    tokenUrl: https://api-shop.beyondshop.cloud/api/oauth/token
    flow: accessCode
    scopes:
      catg:r: No description
      catg:c: No description
      catg:u: No description
      catg:d: No description
      cset:r: No description
      cset:u: No description
      invn:r: No description
      invn:u: No description
      ordn:r: No description
      ordn:u: No description
      lcnt:u: No description
      ordr:r: No description
      ordr:u: No description
      orde:r: No description
      ordp:r: No description
      rfpr:r: No description
      rtpr:r: No description
      rtpr:c: No description
      shpr:r: No description
      shpr:c: No description
      rfpr:u: No description
      shpr:u: No description
      paym:m: Integrate a payment solution
      pymt:r: No description
      pymt:u: No description
      pymt:c: No description
      pymt:d: No description
      prad:r: No description
      prad:c: No description
      prad:d: No description
      prst:r: No description
      prst:u: No description
      prod:r: No description
      prod:c: No description
      prod:d: No description
      prod:u: No description
      prat:r: No description
      prat:c: No description
      prda:r: No description
      prat:d: No description
      prda:u: No description
      scop:r: No description
      shpz:r: No description
      shpz:u: No description
      shpz:c: No description
      shpz:d: No description
      shop:u: No description
      shad:r: No description
      shad:u: No description
      shat:r: No description
      shat:c: No description
      shcl:c: No description
      feat:r: No description
      shim:c: No description
      legl:r: No description
      legl:u: No description
      shat:u: No description
      shat:d: No description
      shim:d: No description
      user:r: No description
      user:c: No description
      user:d: No description
      user:u: No description
  oauth2_application:
    type: oauth2
    tokenUrl: https://api-shop.beyondshop.cloud/api/oauth/token
    flow: application
    scopes:
      catg:r: No description
      catg:c: No description
      catg:u: No description
      catg:d: No description
      cset:r: No description
      cset:u: No description
      invn:r: No description
      invn:u: No description
      ordn:r: No description
      ordn:u: No description
      lcnt:u: No description
      ordr:r: No description
      ordr:u: No description
      orde:r: No description
      ordp:r: No description
      rfpr:r: No description
      rtpr:r: No description
      rtpr:c: No description
      shpr:r: No description
      shpr:c: No description
      rfpr:u: No description
      shpr:u: No description
      paym:m: Integrate a payment solution
      pymt:r: No description
      pymt:u: No description
      pymt:c: No description
      pymt:d: No description
      prad:r: No description
      prad:c: No description
      prad:d: No description
      prst:r: No description
      prst:u: No description
      prod:r: No description
      prod:c: No description
      prod:d: No description
      prod:u: No description
      prat:r: No description
      prat:c: No description
      prda:r: No description
      prat:d: No description
      prda:u: No description
      scop:r: No description
      shpz:r: No description
      shpz:u: No description
      shpz:c: No description
      shpz:d: No description
      shop:u: No description
      shad:r: No description
      shad:u: No description
      shat:r: No description
      shat:c: No description
      shcl:c: No description
      feat:r: No description
      shim:c: No description
      legl:r: No description
      legl:u: No description
      shat:u: No description
      shat:d: No description
      shim:d: No description
      user:r: No description
      user:c: No description
      user:d: No description
      user:u: No description
  basic:
    type: basic